.github/workflows/bazel.yaml

This should prevent issues such as

fix(ci): Use older Ubuntu image to use older GLIBC

---

.github/workflows/bazel.yaml
WORKSPACE.bazel
rs/ic-observability/multiservice-discovery-downloader/BUILD.bazel
rs/ic-observability/multiservice-discovery/BUILD.bazel
rs/ic-observability/multiservice-discovery/src/server_handlers/add_definition_handler.rs
rs/ic-observability/service-discovery/src/registry_sync.rs

Previously we would get:
```
Jan 09 16:38:48.470 ERRO Failed to get latest registry version: Registry Canister Error. Msg: An unknown error occurred in the registry canister: Error on registry_get_value_since: Request failed for http://[2a00:fb01:400:42:5000:6aff:feed:6c6a]:8080/api/v2/canister/rwlgt-iiaaa-aaaaa-aaaaa-cai/query: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 113, kind: HostUnreachable, message: "No route to host" })) using agent Agent { url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv6(2a00:fb01:400:42:5000:6aff:feed:6c6a)), port: Some(8080), path: "/", query: None, fragment: None }, ingress_timeout: 360s, query_timeout: 30s, sender: Blob{04} }
note: run with `RUST_BACKTRACE=1` environment variable to …
```

fix(multiservice-discovery): registry sync returns on missing nns_public_key and msd pings nns before adding the definition

---

.github/workflows/bazel.yaml

This pull request adds a new job to the CI pipeline that automatically pushes containers to the GitHub Container Registry if the branch name starts with "container". 
This can streamline the container development and deployment process.

feat(ci): Automatically push containers if branch name starts with "container"

---

docs/trustworthy-metrics/TrustworthyMetricsAnalytics.ipynb
docs/trustworthy-metrics/trustworthy-metrics.md

- Add a google colaboratory link
- Download data.json from the internet if not present locally (required by google colab)

fix(docs): Update the links for running the trustworthy metrics notebook online

---

docs/trustworthy-metrics/trustworthy-metrics.md

with how to get wallet ID when the canister has been created earlier

Extend CLI usage description

---

.github/dependabot.yml

This pull request enables grouping of dependabot PRs by package ecosystem. It adds a schedule for checking updates to cargo dependencies, python dependencies, and GitHub Actions dependencies. The schedule is set to run every Monday at 07:15 UTC. This change aims to improve the organization and management of dependabot PRs.

feat(ci): Enable grouping of dependabot PRs

---

.github/workflows/bazel.yaml

Should fix https://github.com/dfinity/dre/actions/runs/7626415516/job/20772752035
> Run set -eExou pipefail
> + git clone ***gitlab.com/dfinity-lab/private/k8s/k8s.git
fatal: destination path 'k8s' already exists and is not an empty directory.
Error: Process completed with exit code 128.

fix(ci): Cloning k8s repo to a suitable directory

---

.github/workflows/bazel.yaml

The CI job does not have the necessary privileges to push to main at the moment, and this might not be a great idea anyway. Example failed run: https://github.com/dfinity/dre/actions/runs/7648727685/job/20842002552

feat(ci): Create a PR on nightly CI runs instead of directly pushing to main

---

.github/workflows/main.yaml
.github/workflows/manage-runner-post/action.yaml
.github/workflows/prepare-release.yml
.github/workflows/update-k8s-deployments/action.yaml

Composite actions do not have access to secrets, by default. Secrets need to be explicitly passed to them.

fix(ci): Correctly pass secrets to the k8s-deployments composite actions

---

rs/ic-observability/multiservice-discovery/src/definition.rs
rs/ic-observability/multiservice-discovery/src/server_handlers/add_definition_handler.rs
rs/ic-observability/multiservice-discovery/src/server_handlers/dto.rs
rs/ic-observability/multiservice-discovery/src/server_handlers/replace_definitions_handler.rs

I did not get to do this earlier because we had crunch, but now that I have a little bit more time, I have invested it into cleaning up this code to remove duplication and make the two management operations more symmetrical.
There is another cleanup I have in mind which is to marry the thread join handle into the definition so that we don't have to carry two separate `Vec[]`s (one for definitions and one for their join handles), which is nasty and can induce bugs later.  That will have to wait until at least tomorrow, though.
Functionality is equivalent and has not changed.

Simplify the definition management code in multiservice-discovery.

---

.bazelrc
.github/workflows/main.yaml
bazel/workspace_status.sh
rs/cli/BUILD.bazel
rs/cli/build.rs
rs/cli/src/cli.rs
rs/cli/src/main.rs

Before the change, with bazel builds:
```
./bazel-bin/rs/cli/dre --version
INFO  dre > Running version 
dre 
```
After the change:
```
$ bazel run //rs/cli:dre -- --version
[...]
INFO  dre > Running version 0.2.0-5aaa4fa-dirty
dre 0.2.0-5aaa4fa-dirty
```
The version is picked up automatically from `Cargo.toml` and git. Build is done as usual.
Bazel changes based on https://github.com/bazelbuild/rules_rust/blob/fe610dab73c3c61560a547bc661177dd5115fed7/examples/version_stamping/BUILD.bazel#L15

fix(bazel): Update build configuration and version information

---

.github/workflows/update-dependencies.yaml

Using `GITHUB_TOKEN` results in the workflow not being triggered, as per https://github.com/orgs/community/discussions/25602

fix(ci): Use a GitHub PAT when creating PR automatically

---

rs/ic-observability/multiservice-discovery/src/definition.rs
rs/ic-observability/multiservice-discovery/src/main.rs

The following provides a wrapper around `RunningDefinition` used for testing.
It fixes previous `sync` to also load the in-mem cache

Fixed sync_and_stop to load in mem cache

---

Cargo.Bazel.lock
Cargo.lock
rs/cli/Cargo.toml
rs/cli/src/cli.rs
rs/cli/src/main.rs
rs/cli/src/registry_dump.rs
rs/ic-management-backend/src/registry.rs

The PR allows you to:
1. Do a dump of the mainnet registry of latest version. Here a temporary folder will be created and deleted at the end of the sync.
```bash
bazel run //rs/cli:dre -- dump-registry
```
2. Do a dump of a custom networks registry of some version.
```bash
bazel run //rs/cli:dre -- --network <nns-url> dump-registry --version <version> 
```
3. Do a dump of a cached registry. The cached registry will first be upgraded to the latest version and then the specified version will be dumped. If the `--path` parameter is passed the cached registry will not be destroyed at the end of the action.
```bash
bazel run //rs/cli:dre -- dump-registry --version <version> --path <path>
```

feat(dre): added registry dump

---

k8s/boundary-node-service-discovery/boundary-node-service-discovery.py

Forgotten fix when the `ic` parameter for `mainnet` in `multiservice-discovery` was moved to `mercury`

feat(k8s): adding parameter for ic name in boundary node service discovery

---

Cargo.Bazel.lock
Cargo.lock
rs/cli/Cargo.toml
rs/cli/src/main.rs
rs/cli/src/registry_dump.rs
rs/decentralization/src/nakamoto/mod.rs
rs/ic-observability/multiservice-discovery/src/definition.rs

- Instead of expecting from the user to interpret Vec<u8> as principals (somehow), we can do this in the code directly, and show principals as principals
- Make the dump more in line with what ic-admin shows (in ic-admin get-topology)
- Show the node reward table as well
- Use native JSON serialize for the dump, instead of manually crafting the wrapper struct
- Use the same dir that the registry sync uses, to avoid the slow re-downloading the entire mainnet registry on every execution

feat(registry-dump): Interpret vec<u8> data in registry structs as corresponding types

---

rs/ic-observability/multiservice-discovery/src/definition.rs
rs/ic-observability/multiservice-discovery/src/main.rs
rs/ic-observability/multiservice-discovery/src/metrics.rs
rs/ic-observability/multiservice-discovery/src/server_handlers/delete_definition_handler.rs
rs/ic-observability/multiservice-discovery/src/server_handlers/mod.rs
rs/ic-observability/multiservice-discovery/src/server_handlers/replace_definitions_handler.rs

Use a private data structure to track per-network metrics, then use that data structure as data source for the metrics callbacks.  The once-added callbacks can then serve the metrics for registered definitions.
In addition to that, when a definition ends, we deregister it from the per- network metrics data structure, so we stop serving metrics about it.
We are no longer using Tokio mutexes since this would require async closures for the callbacks, and async closures are unstable.  std::sync::Mutex works perfectly OK for this use and, in fact, Tokio documentation states that standard mutexes can work fine with Tokio code, and should be preferred in most cases.
https://docs.rs/tokio/1.24.2/tokio/sync/struct.Mutex.html#which-kind-of-mutex-should-you-use indicates we should use the standard …

Refactor metrics to simplify updating the values

---

rs/ic-observability/sns-downloader/src/downloader_loop.rs

Adding a forgotten `limit` parameter since by default the limit is 20. Right now there are 23 SNSes meaning 3 were never aquired.
Apart from that added sorting of SNSes and Canisters in each Sns by `canister_id` so we have deterministic hashing and we don't reload vector all the time.

fix(sns-downloader): fixing limit and better hashing

---

.github/workflows/msd-diff.yaml
rs/ic-observability/multiservice-discovery/src/definition.rs
rs/ic-observability/multiservice-discovery/src/main.rs

* Used for MSD test: Add arg `--skip-update-local-registry` to avoid syncing the local registry with remote registry canister (which cause flaky test)

Add CLI arg to skip the update of the local registry

---

rs/ic-observability/multiservice-discovery/src/definition.rs
rs/ic-observability/multiservice-discovery/src/main.rs

* Change the way we persist definitions to disks to rewrite them every time we add/remove definitions from the server

Persist definitions to disk on add/remove

---

rs/cli/src/cli.rs
rs/cli/src/ic_admin.rs
rs/cli/src/main.rs

* Fix typo in proposal to remove firewall rules.
* Fix signature of remove command being called.
* Batch multiple operations so we can at least remove / modify / add multiple rules in one proposal.
* Add standard title, summary and motivation parameters to firewall management.
Before we do the batching, we sort the rules by modification slot
then we reverse the order of the rules list, and then we do the 
batching.  This ensures that the modifications happen in an order
that will not conflict between each other (what does it mean "add 
rule in position 3" if rule in position 2 was removed prior to 
that?).

Fix firewall rule management.

---

rs/cli/src/main.rs

I spent 10 minutes trying to grep for the error, to no avail.  When I had to spend another 5 minutes adding `panic()`s to the code in order to suss this one out, I decided to do something about it.

Clarify errors in `main()` coming from the governance canister client.

---

rs/cli/src/main.rs

Neuron is not actually required for this operation.

fix(dre): DRE-147 Do not require neuron id for fetching trustworthy metrics

---

.github/workflows/update-k8s-deployments/action.yaml

This will provide us with flexibility to deploy from separate branches in the DRE repo (if needed), and still keep the number of MRs in k8s repo small and bounded.

feat(ci): Maintain up to 1 open MR in the k8s repo per DRE branch

---

.github/workflows/prepare-release/action.yaml
Cargo.Bazel.lock
Cargo.lock
rs/cli/BUILD.bazel
rs/cli/Cargo.toml
rs/cli/build.rs
rs/cli/src/build_script_.rs
rs/cli/src/cli.rs
rs/cli/src/ic_admin.rs
rs/cli/src/lib.rs
rs/cli/src/main.rs
rs/cli/src/operations/hostos_rollout.rs
rs/cli/src/parsed_cli.rs

Added functionality to build script (now its `src/build_script_.rs` because of Bazel) to generate autocompletion scripts.
To generate completions in `~/Downloads/completions` using cargo:
```bash
COMPLETIONS_OUT_DIR=~/Downloads/completions cargo build --bin dre (--release)
```
To generate completions using bazel (After this they will be present in `bazel-out/k8-opt/bin/rs/cli/build_script.out_dir/completions`):
```bash
bazel build //rs/cli:dre
```
Additional notes:
* Added these scripts to releases. If someone finds them useful they can download them, if not, they can opt out.

feat(cli): implementing completions

---

rs/ic-observability/multiservice-discovery/src/definition.rs
rs/ic-observability/service-discovery/src/registry_sync.rs

We have been quite good with regards to handling interrupts / SIGTERMs almost from the very start in MSD.  However, a small oversight with regards to initial sync caused https://github.com/dfinity/dre/issues/314 , which in turn causes the daemon to freeze upon shutdown if any definition failed its initial sync.  The root cause is that the thread terminates on its own, not polling its end of the ender channel used to shut it down.
This PR fixes the issue.
In addition to that, we now also retry initial syncs just as failed incremental syncs are retried.  This adds robustness in the face of temporary network outages just as MSD is starting to execute.

Introduce interrupt and retry handling to initial definition sync.

---

scripts/free-up-nodes.py

Adding an automation script for removing a list of nodes from their subnets.
The script fetches JSON data of nodes from the internal dashboard, groups the nodes by their subnet IDs, and replaces the nodes in each subnet using the 'dre' command-line tool.
This script will free up nodes for redeployment with IPv4 configuration in addition to the usual IPv6 configuration.

feat(script): Automation script for removing nodes from subnets

---

bin/optimize-bazel-cache.sh

Bazel cache currently does not fit into the 10GB quota on GitHub.

feat(ci): Improve the bazel cache optimization

---

rs/ic-observability/config-writer-common/src/filters.rs
rs/ic-observability/multiservice-discovery-shared/src/builders/log_vector_config_structure.rs
rs/ic-observability/multiservice-discovery-shared/src/contracts/target.rs
rs/ic-observability/multiservice-discovery/src/definition.rs
rs/ic-observability/multiservice-discovery/src/server_handlers/export_prometheus_config_handler.rs
rs/ic-observability/multiservice-discovery/src/server_handlers/export_targets_handler.rs
rs/ic-observability/prometheus-config-updater/src/custom_filters.rs
rs/ic-observability/prometheus-config-updater/src/prometheus_config.rs
rs/ic-observability/service-discovery/src/job_types.rs
rs/ic-observability/service-discovery/src/lib.rs

Added a flag `is_api_bn` to all targets on `/targets` path since api boundary nodes have a regular node record.
Generated prometheus config on `/prom/targets` looks like:
```json
{
"targets": [
"http://[2a00:fb01:400:200:6801:95ff:fed7:d475]:9091/"
],
"labels": {
"ic": "api-bns",
"ic_node": "dj5ch-uokcu-wctk6-b4mxs-bogcv-tg4xj-4ef2j-wcdsg-q2ngr-ya3ee-fqe",
"job": "orchestrator"
}
}
{
"targets": [
"https://[2a00:fb01:400:200:6801:95ff:fed7:d475]:9100/metrics"
],
"labels": {
"ic": "api-bns",
"ic_node": "dj5ch-uokcu-wctk6-b4mxs-bogcv-tg4xj-4ef2j-wcdsg-q2ngr-ya3ee-fqe",
"job": "node_exporter"
}
}
{
"targets": [
"https://[2a00:fb01:400:200:6800:95ff:fed7:d475]:9100/metrics"
],
"labels": {
"ic": "api-bns",
"ic_node": "dj5ch-uokcu-wctk6-b4mxs-bogcv-tg4xj-4ef2j-wcdsg-q2ngr-ya3ee-fqe",
"job": …
```

feat(msd): adding api boundary nodes to multiservice discovery and downloader

---

Cargo.Bazel.lock
Cargo.lock
rs/cli/Cargo.toml
rs/cli/src/cli.rs
rs/cli/src/main.rs
rs/ic-canisters/src/governance.rs
rs/ic-canisters/src/lib.rs

Currently supports:
1. Listing pending proposals => maps to [`get_pending_proposals`](https://dashboard.internetcomputer.org/canister/rrkah-fqaaa-aaaaa-aaaaq-cai#get_pending_proposals)
2. Listing proposal with filtering => maps to [`list_proposals`](https://dashboard.internetcomputer.org/canister/rrkah-fqaaa-aaaaa-aaaaq-cai#get_pending_proposals)

feat(dre): listing proposals

---

release-controller/governance.py
release-controller/reconciler.py

source: https://stackoverflow.com/questions/32763720/timeout-a-file-download-with-python-urllib

fix(release-controller): [DRE-166] use requests instead of urllib, to handle timeouts

---

Cargo.Bazel.lock
Cargo.lock
rs/ic-canisters/Cargo.toml
rs/ic-canisters/src/management.rs

Some subnets are still running the old version which was preventing the dre tool from fetching trustworthy metrics.

fix(dre): Add compatibility in fetching trustworthy metrics from old subnet versions

---

Cargo.Bazel.lock
Cargo.lock
rs/cli/Cargo.toml
rs/cli/src/registry_dump.rs
rs/ic-management-backend/src/registry.rs

- Version running on unassigned nodes
- Elected GuestOS versions
- Elected HostOS versions

feat(dre): Include more info in the registry dump

---

rs/cli/src/cli.rs
rs/cli/src/ic_admin.rs
rs/cli/src/main.rs
rs/cli/src/runner.rs
rs/ic-management-backend/src/registry.rs
rs/ic-management-types/src/lib.rs
rs/rollout-controller/src/actions/mod.rs
rs/rollout-controller/src/main.rs

- revise-elected-guestos-versions
- revise-elected-hostos-versions
- deploy-guestos-to-all-subnet-nodes
- deploy-guestos-to-all-unassigned-nodes
- deploy-hostos-to-some-nodes

feat(dre): Update the DRE cli tool to work with the new IC-OS proposals

---

rs/cli/src/detect_neuron.rs
rs/cli/src/general.rs
rs/cli/src/ic_admin.rs
rs/cli/src/main.rs
rs/cli/src/registry_dump.rs
rs/cli/src/runner.rs
rs/ic-management-backend/src/health.rs
rs/ic-management-backend/src/registry.rs
rs/ic-management-types/src/lib.rs

Tested on staging with
```
❯ bazel run //rs/cli:dre -- --network staging update-unassigned-nodes --yes
```
custom private key pem can be provided with e.g.
```
❯ bazel run //rs/cli:dre -- --network staging --private-key-pem <custom-path.pem> update-unassigned-nodes --yes
```

feat(dre): [REL-1517] Auto-pick automation neuron for updating unassigned nodes

---

rs/cli/src/cli.rs
rs/cli/src/ic_admin.rs
rs/cli/src/main.rs

Make the subcommand names more in line with the ic-admin command names.
Also, fix a few things for the HostOS rollout:
- fix the "required" arguments for hostos rollouts to make usage clearer
- use the release automation neuron for HostOS rollouts by default; user is still able to override those defaults

chore: Adjust and optimize the subcommands for host and version elect

---

rs/cli/src/registry_dump.rs
rs/ic-management-backend/src/health.rs

This PR builds upon `dump-registry` command. It adds node status to the node output which looks like the following:
```json
{
"node_id": "zxxo4-abmdb-uj3ok-cbj4k-is36g-b5o2d-c6akl-vmgyu-d2wie-hgr3y-uae",
"xnet": {
"ip_addr": "2a00:fc0:5000:300:6801:4fff:fe2e:6276",
"port": 2497
},
"http": {
"ip_addr": "2a00:fc0:5000:300:6801:4fff:fe2e:6276",
"port": 8080
},
"node_operator_id": "3xiew-2wo3x-tnbn2-o7kok-wwsnw-7koo2-gna5r-rlrt3-zotsh-dwpg6-kae",
"chip_id": null,
"hostos_version_id": "e268b9807f1ab4ae65d7b29fe70a3b358d014d6a",
"public_ipv4_config": null,
"subnet_id": null,
"dc_id": "mb1",
"node_provider_id": "wdjjk-blh44-lxm74-ojj43-rvgf4-j5rie-nm6xs-xvnuv-j3ptn-25t4v-6ae",
"status": "Healthy"
},
{
"node_id": "zzhpj-v2jd7-sfsts-suhfq-k4otv-fy5n3-tsogo-6jrk2-adsxv-c3jwu-xqe",
"xnet": { …
```

feat(dre): implementing checks for correct node rewards set for node operators

---

rs/cli/src/cli.rs

Before:
```bash
dre --help                                                               
INFO  dre > Running version 0.4.0-9f8fa09
INFO  dre > Binary up to date.
Tooling for managing the Internet Computer
Usage: dre [OPTIONS] <COMMAND>
Commands:
der-to-principal         
subnet                   Manage an existing subnet
get                      Get a value using ic-admin CLI
propose                  Place a proposal using the ic-admin CLI
update-unassigned-nodes  Place a proposal for updating unassigned nodes config
version                  Manage replica/host-os versions blessing
hostos                   Rollout hostos version
nodes                    Manage nodes
vote                     Vote on our proposals
trustworthy-metrics      Trustworthy Metrics
registry …
```

fix(dre): not displaying sensitive pin when running help command

---

release-controller/release_notes.py

This re-classification was triggering wrongly in some cases, marking feature commits as "other" just because the feature commit was touching many teams.
This is not needed anymore since conventional commits are getting enforced in the IC repo.

fix(release-notes): Drop the re-classification of commits to "other" in some cases

---

rs/log-fetcher/src/main.rs

Previously, if the `__CURSOR` wasn't present we would start fetching only the newest logs. While convenient it we had some issues where we would lose logs or have to refetch from the start and this would help us achieve that more easily. When the new target is added we will start fetching logs from the start of their journal

chore: changing default behavior if cursor is not present

---

rs/cli/src/main.rs

Binaries compiled without .git directory do not have `-abcd` suffix in their version, which breaks their execution with
```
Error: Version '0.4.0' doesn't follow expected naming
```
With this change we now properly check if the version follows semantic versioning.

feat: Support dre binary compiled without .git

---

rs/cli/src/operations/hostos_rollout.rs

The test somehow didn't have these fields set. We should look into why the CI didn't catch this.

fix(dre): Fix the test for the hostos rollout, add api-boundary-nodes

---

rs/cli/src/cli.rs
rs/cli/src/ic_admin.rs
rs/cli/src/main.rs
rs/cli/src/runner.rs

The other parameters are optional, of course. We just pass through any unrecognized arguments to ic-admin, expecting that ic-admin will be able to parse them properly, or complain otherwise.

feat(dre): [DRE-178] Accept additional parameters for subnet creation

---

.github/workflows/msd-diff.yaml
rs/ic-observability/multiservice-discovery-shared/src/builders/prometheus_config_structure.rs

This PR adds a new label to the `/prom/targets` endpoint that is being used from victoria metrics to scrape targets.
The new labels only affect api boundary nodes. Other targets won't get the new label.
Output looks like:
```json
...
// Standard nodes
{
"targets": [
"http://[2401:3f00:1000:23:6801:b3ff:fe4d:4fc7]:9091/"
],
"labels": {
"ic": "mercury",
"ic_node": "kqurf-2p6ca-j4zte-3wkx5-rovid-kgn7s-yih6m-mj74k-claji-7uoje-vae",
"job": "orchestrator"
}
},
{
"targets": [
"https://[2401:3f00:1000:23:6801:b3ff:fe4d:4fc7]:9100/metrics"
],
"labels": {
"ic": "mercury",
"ic_node": "kqurf-2p6ca-j4zte-3wkx5-rovid-kgn7s-yih6m-mj74k-claji-7uoje-vae",
"job": "node_exporter"
}
},
{
"targets": [
"https://[2401:3f00:1000:23:6800:b3ff:fe4d:4fc7]:9100/metrics"
],
"labels": {
"ic": "mercury",
"ic_node": …
```

feat(msd): adding label for api boundary nodes

---

Cargo.Bazel.lock
Cargo.lock
rs/ic-observability/multiservice-discovery/Cargo.toml
rs/ic-observability/multiservice-discovery/src/metrics.rs

Example of the metric:
```text
http_server_active_requests{http_request_method="GET",url_scheme="http",otel_scope_name="axum-app"} 1
msd_definitions_load_errors{network="mercury",otel_scope_name="axum-app"} 0
msd_definitions_load_successful{network="mercury",otel_scope_name="axum-app"} 1
msd_definitions_sync_errors{network="mercury",otel_scope_name="axum-app"} 0
msd_definitions_sync_successful{network="mercury",otel_scope_name="axum-app"} 1
msd_definitions_sync_ts{network="mercury",otel_scope_name="axum-app"} 1718637276
target_info{service_name="unknown_service",telemetry_sdk_language="rust",telemetry_sdk_name="opentelemetry",telemetry_sdk_version="0.22.1"} 1
```

feat(msd): adding timestamp of last successful sync

---

release-controller/release_notes.py
scripts/release-notes.py

Addresses the following complaint:
```
author: Maks Arut | 48afaffa4 Execution: limit the max number of nodes in compute_initial_*_dealings request argument  (48afaff ) was not in the release notes. 
```
openchat link: https://oc.app/community/32l35-yaaaa-aaaar-aw57q-cai/channel/78010556105983937984590438937075688039/92?open=true
slack link: https://dfinity.slack.com/archives/CGZJ7G1J6/p1718623326453169

fix(release-notes): Do not exclude "canister" changes in release notes

---

release-controller/reconciler.py
release-controller/watchdog.py

Kubernetes will automatically restart it in this case.
Some 3rd party libraries that we use do not implement timeouts properly.
Closes DRE-184

feat(release-controller): Kill the release controller if it gets stuck

---

rs/cli/src/cli.rs
rs/cli/src/general.rs
rs/cli/src/ic_admin.rs
rs/cli/src/main.rs
rs/cli/src/runner.rs

- this makes it more consistent with ic-admin
- it's backwards compatible since the old arguments are still accepted

chore(dre): Rename --simulate to --dry-run

---

rs/cli/src/main.rs

The requirement of --motivation was an oversight in the earlier code, since we're only asking for help on subnet creation params.

chore(dre): Do not require --motivation if --help-other-args is provided

---

rs/cli/src/registry_dump.rs
rs/cli/src/runner.rs
rs/ic-management-backend/src/public_dashboard.rs
rs/ic-management-backend/src/registry.rs
rs/np-notifications/src/health_check.rs

The public dashboard contents that we use change very infrequently, every few months. So no need to re-fetch them on every request.

feat(dre): Cache public dashboard API response for 1h

---

release-controller/google_docs.py
release-controller/reconciler.py

chore(release): Do not regenerate release notes all the time, to save on time and docker hub rate limit

---

Cargo.Bazel.lock
Cargo.lock
Cargo.toml
rs/cli/Cargo.toml
rs/cli/src/main.rs

With this fix we will be able to:
1. Automatically reject upgrades if stdin is not a tty (useful if running in docker container)
To test this you can run:
```bash
echo "test" | dre registry
```
2. Set an environment variable to skip the check (useful if running in some scripts that are still run from terminal)
To test this you can run:
```bash
DRE_REFUSE_UPDATE=1 dre registry
```

fix(dre): asking for update everywhere

---

Cargo.Bazel.lock
Cargo.lock
Cargo.toml
rs/cli/Cargo.toml
rs/cli/src/cli.rs
rs/cli/src/main.rs

As it says, this PR moves checking for new releases to a background thread, meaning it doesn't halt the execution of the commands. 
Example of running any command when there is a new release available:
```bash
./target/debug/dre registry > /dev/null                                                        
INFO  dre > Running version 0.4.0-2faf0cb-dirty
INFO  dre::ic_admin > Using ic-admin: /home/nikola/bin/ic-admin.revisions/b39f782ae9e976f6f25c8f1d75b977bd22c81507/ic-admin
INFO  ic_management_backend::registry > Using local registry path for network mainnet: /home/nikola/.cache/ic-registry-cache/mainnet/local_registry
INFO  ic_management_backend::git_ic_repo > IC git repo path: /home/nikola/.cache/git/ic, lock file path: /home/nikola/.cache/git/ic.lock
INFO  dre …
```

refactor(dre): implementing background checks for upgrading

---

rs/cli/src/runner.rs

With this, running `dre get` now finishes in 0.2s.
Without the change, running the same command takes 13.3s.

feat(dre): Speed up get operations by not preparing a neuron and the registry

---

rs/cli/src/runner.rs

Should resolve the problem:
```
thread 'main' panicked at rs/cli/src/runner.rs:93:14:
Failed to get mutable reference
```

fix(dre): Remove unnecessary Arc::clone

---

rs/cli/src/main.rs

Frequent update checks were causing the following error:
```
{"message":"API rate limit exceeded for 141.195.95.130. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

feat(dre): Only check for updates once per day

---

.pre-commit-config.yaml
Cargo.Bazel.lock
k8s/oci_images.bzl
rs/oci_images.bzl

Convenience refactor for easier to use targets.
Previously to import a docker image into local registry we would have to run something like:
```
bazel run //rs/ic-observability/multiservice-discovery:multiservice-discovery-tarball
```
Now we can just run:
```
bazel run //rs/ic-observability/multiservice-discovery:tarball
```
And the target names are the same across all binaries.
Contains additional upgrade for pylint in pre-commit so that it works in envs with python3.12: 
Linked issue: https://github.com/pre-commit/pre-commit/issues/3041

refactor: renaming bazel targets

---

Cargo.Bazel.lock
Cargo.lock
rs/cli/Cargo.toml
rs/cli/src/general.rs

I noticed that the first "vote" log line overwrites whatever the last log line. Fixed here.
Also, show the date & time of the voting in the logs, for easier auditing.

feat(dre): Show the date+time when voting, and do not stomp on previous logs

---

rs/cli/src/runner.rs

Run network Heal command iteratively to bring more clarity to the output

Fix network Heal command

---

node-labels/mainnet.yaml

The ipv6 address changed after changing the motherboard, and it was provided by the node provider.

fix(dashboard): Adjust the node label for zh5-dll25

---

.github/workflows/prepare-release/action.yaml

Migrated to a subcommand that can be used in `~/.bashrc`/`~/.zshrc`
```bash
. $(dre completions -s <bash,zsh,...>)
```

chore(ci): removing dre completions from releases

---

Cargo.toml
rs/cli/src/commands/upgrade.rs

Goes along with: #623 
When #623 is merged new release will break the upgrading code. After downloading the newest (or building from source) the tool will handle all future architectures and os versions we decide to support.

feat(dre): allowing self update for macos

---

rs/cli/src/commands/mod.rs
rs/cli/src/commands/registry.rs
rs/cli/src/ctx.rs
rs/ic-management-backend/src/lazy_registry.rs

Useful if the NNS is down to allow at least some functionality of the tool.

feat(dre): adding an option for dre to not sync with the nns

---

.github/workflows/qualify.yaml

DRE requested that the qualifier workflow automatically gets kicked off when the `Release Testing` [workflow](https://github.com/dfinity/ic/blob/master/.github/workflows/release-testing.yml) succeeds. This change allows the qualifier workflow to be triggered by an external workflow.
This still needs to be tested and I may need to make more changes later.

feat(IDX): add trigger for qualifier workflow

---

release-controller/release_notes.py
release-controller/test_release_notes.py

Migrate target disk-img.tar.gz -> disk-img.tar.zst
The GZ images were deprecated and removed a few days ago.  Release controller needs to switch to using ZST images for its build / changelog generation routines.

Fix release-controller to use the new ZST images

---

Cargo.Bazel.lock
Cargo.lock
Cargo.toml
WORKSPACE.bazel
docker/Dockerfile
ic-revisions.json
poetry.lock
pylib/ic_admin.py
release-controller/release_index.py
requirements.txt
rs/cli/Cargo.toml
rs/cli/src/auth.rs
rs/cli/src/commands/proposals/filter.rs
rs/cli/src/commands/proposals/mod.rs
rs/cli/src/commands/registry.rs
rs/cli/src/ic_admin.rs
rs/ic-management-backend/src/registry.rs
rs/ic-observability/multiservice-discovery/Cargo.toml
rs/ic-observability/node-status-updater/Cargo.toml
rs/ic-observability/service-discovery/src/registry_sync.rs

This PR updates poetry (Python) and cargo (Rust) dependencies and IC repository dependencies

chore: Update dependencies

---

rs/decentralization/src/network.rs

This commit modifies the `DecentralizedSubnet` implementation in the `network.rs` file to prefere existing nodes in the subnet when selecting the best results.
This change ensures that the same nodes are retained in the subnet if they are already there.

fix(dre): [DRE-241] Prefer existing nodes in subnet when selecting best results

---

rs/cli/src/runner.rs
rs/cli/src/subnet_manager.rs
rs/decentralization/src/lib.rs
rs/decentralization/src/nakamoto/mod.rs
rs/decentralization/src/network.rs
rs/decentralization/src/subnets.rs
rs/ic-management-backend/src/endpoints/query_decentralization.rs
rs/ic-management-backend/src/lazy_registry.rs
rs/ic-management-backend/src/registry.rs
rs/ic-management-backend/src/subnets.rs

This should make it easier to understand the motivation behind the proposal, and to verify the proposal payload.

feat(dre): [DRE-240] Add more info to the subnet membership change proposals

---

Cargo.Bazel.lock
Cargo.lock
Cargo.toml
rs/qualifier/Cargo.toml
rs/qualifier/src/main.rs
rs/qualifier/src/version_selector.rs

This PR addresses a long known issue of qualifying from wrong versions.
The issue (as explained by David Derler):
> The issue I’m referring to is the following.
mainnet_revisions.json is updated when the NNS is updated to version v1. This happens on day X (e.g. Monday).
> * On day X - k (say Thursday of the previous week) we, most likely already have a qualified v2
> * On day X + l (say Thursday of the week following the rollout of v1 ) we qualify another release v3.
> * On day X + m (say Monday of the following week) v2 hits the NNS.
> * After that v3 rollout starts and will hit the NNS on day X + m + 7.
> So the issue is that the qualification test runs between v1 <-> v3 as opposed to v2 <-> v3.
The fix might be as easy as testing against the version of io67a in the …

feat(qualification): adding resolving version from nns via rollout dashboard

---

rs/decentralization/src/lib.rs

The duplicates were likely added in some merge conflict resolution

fix(dre): Fix the duplicate output (printout) of the SubnetChangeResponse

---

.github/workflows/qualify.yaml

One dumb thing about this is that of how secrets work:
When this is run from our repo, say via a `workflow_dispatch` event, it will say that our `Airflow` bot created a message.
When this is  run automatically from ic repo, it will say that their bot created it.

feat: slack notification about quali

---

rs/cli/src/runner.rs
rs/decentralization/src/nakamoto/mod.rs
rs/decentralization/src/network.rs
rs/decentralization/src/subnets.rs
rs/ic-management-backend/src/lazy_registry.rs

- Provide more information in the membership change proposals, to clarify why a particular number of nodes was replaced to optimize decentralization, and to quantify the gain from the replacement
- Refactor the subnet healing to skip subnets with open proposals
- Some variable renamings
- Improving the lazy loading of registry data and proposals

feat: Optimize subnet healing process

---

.github/workflows/update-dependencies.yaml

Let this PR serve to remind the team to not update dependencies on Fridays 🙂

chore: update deps only on Monday

---

dashboard/packages/app/src/components/subnets/NodeSearch.tsx
rs/cli/src/operations/hostos_rollout.rs
rs/decentralization/src/nakamoto/mod.rs
rs/decentralization/src/network.rs
rs/ic-management-backend/src/lazy_registry.rs
rs/ic-management-backend/src/node_labels.rs
rs/ic-management-backend/src/registry.rs
rs/ic-management-backend/src/subnets.rs
rs/ic-management-types/src/lib.rs

This pull request removes the legacy "decentralized" node flag from the codebase. It also includes various code cleanup changes.

chore(decentralization): Remove legacy decentralized node flag and clean up code

---

rs/cli/src/ic_admin.rs

Adds back the output of ic admin propose command to stdout in the form of:
```diff
./target/debug/dre --private-key-pem ~/.config/dfx/identity/bootstrap-super-leader/identity.pem --network staging -y propose propose-to-revise-elected-guestos-versions --summary "Testing" --replica-versions-to-unelect 26d5f9d0bdca0a817c236134dc9c7317b32c69a5
2024-08-26T12:04:03.234Z INFO  dre > Running version 0.5.1-3640baca-dirty
2024-08-26T12:04:03.390Z INFO  dre::ic_admin > Using ic-admin c7d517db67fde740f5e3338c86e95b4ec8beb00a because lock file was created less than 24 hours ago
Title: Retire IC replica version(s)
Summary: Testing
Payload: ReviseElectedGuestosVersionsPayload {
replica_version_to_elect: None,
release_package_sha256_hex: None,
release_package_urls: [], …
```

fix(dre): adding back output of proposals

---

Cargo.Bazel.lock
Cargo.lock
Cargo.toml
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics-frontend/src/App.tsx
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics-frontend/src/components/NodeList.tsx
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics-frontend/src/components/NodePage.tsx
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics-frontend/src/components/NodeProviderPage.tsx
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics-frontend/src/components/RewardTable.tsx
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics-types/src/types.rs
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics/Cargo.toml
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics/src/computation_logger.rs
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics/src/lib.rs
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics/src/operations_tracker.rs
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics/src/rewards_manager.rs
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics/trustworthy-node-metrics.did

1. Add logging at each step of the computation
2. Adapt test for this
3. Use int for representing `rewards_percent` `rewards_reduction`
computation_log example:
```
INPUT:
timestamp_nanoseconds: 1, num_blocks_proposed: 10,  num_blocks_failed: 0
timestamp_nanoseconds: 2, num_blocks_proposed: 6,  num_blocks_failed: 4
timestamp_nanoseconds: 3, num_blocks_proposed: 7,  num_blocks_failed: 3
REWARDS COMPUTATION LOG:
STEP 1: Computing Total Failed Blocks: 0 + 4 + 3 = 7
STEP 2: Computing Total Proposed Blocks: 10 + 6 + 7 = 23
STEP 3: Computing Total Blocks: 7 + 23 = 30
STEP 4: Computing Total Failure Rate: 7 / 30 * 100 = 23
STEP 5: Linear Reduction Y change: 23 - 10 = 13
STEP 6: Linear Reduction X change: 70 - 10 = 60
STEP 7: Linear Reduction Percent: 13 / 60 * 100 = 22
STEP 8: Total Rewards …
```

Add Rewards Computation logging for audit

---

rs/cli/src/ctx.rs
rs/cli/src/runner.rs
rs/ic-management-backend/src/lazy_git.rs

Another PR in the line of making `dre` more testable. With this included we should be able to easily mock fetching information about the branches and releases.

refactor: lazy git

---

rs/cli/src/ctx.rs
rs/cli/src/operations/hostos_rollout.rs
rs/cli/src/runner.rs
rs/ic-management-backend/src/endpoints/mod.rs
rs/ic-management-backend/src/lazy_registry.rs
rs/ic-management-backend/src/proposal.rs
rs/ic-management-backend/src/registry.rs
rs/ic-management-backend/src/release.rs

This PR migrates `ProposalAgent` to be a trait to support easier mocking. The real solution would be to migrate `ProposalAgent` functionality into `GovernanceCanisterWrapper` because it includes only calls for that canister. But to not polute this PR with extra code this was done as a step in between.

chore: refactoring proposals agent to increase testability

---

Cargo.Bazel.lock
Cargo.lock
Cargo.toml
rs/cli/Cargo.toml
rs/cli/src/auth.rs
rs/cli/src/commands/mod.rs
rs/cli/src/commands/vote.rs
rs/cli/src/ctx.rs
rs/cli/src/main.rs
rs/qualifier/src/qualify_util.rs
rs/rollout-controller/src/actions/mod.rs

The fundamental change in this PR could have been described as reducing ambiguity in command line processing for the authentication options, by exploiting the Rust type system.  The path was somewhat more tortuous.
Chiefly, we simplify a lot of the inner function calls, which no longer require four different arguments that could each wrongly and independently have missing values when they should never have them.  Argument combinations that are invalid must be rejected.
* Authentication selection:
* Use of `--private-key-pem` with any HSM-related argument is forbidden.
* Hardware security module detection now allows the user to narrow down to either an HSM slot, or an HSM key ID, or both, or let autodetection take place as usual.
* When none are specified, autodetection remains unchanged …

Refactor authentication detection.

---

.github/workflows/manage-runner-post/action.yaml

https://github.com/dfinity/dre/actions/runs/10719910936/job/29725015788

fix(ci): Update cache job fix

---

rs/cli/src/ctx.rs

If the command has `IcAdminRequirement` set to `None` / `Anonymous` we don't need to detect any auth.
Ideally we should rename `IcAdminRequirement` to something like `Auth` and have multiple levels:
1. None - just nothing
2. Anonymous - anonymous
3. Signer - `private-key-pem` / hsm trio
4. Neuron - Signer + `neuron-id`
5. OverridedBy - Custom Neuron for network
But that is a bigger refactor

fix: initialization logic

---

.github/workflows/build/action.yaml
bin/cargo-deny-checks.sh

--warn unmaintained causes Cargo Deny to ignore the exceptions we have coded into deny.toml.
Therefore removed.
Also restored -D to intentionally cause failures when this is executed, so that a commit is not possible to be merged when it introduces a problem.

Restore original, intended behavior of cargo deny.

---

Cargo.Bazel.lock
Cargo.lock
Cargo.toml
rs/cli/Cargo.toml
rs/cli/src/commands/hostos/rollout_from_node_group.rs
rs/cli/src/commands/registry.rs
rs/cli/src/commands/update_authorized_subnets.rs
rs/cli/src/operations/hostos_rollout.rs
rs/cli/src/runner.rs
rs/cli/src/unit_tests/version.rs
rs/decentralization/Cargo.toml
rs/decentralization/src/lib.rs
rs/decentralization/src/nakamoto/mod.rs
rs/decentralization/src/network.rs
rs/decentralization/src/subnets.rs
rs/ic-management-backend/Cargo.toml
rs/ic-management-backend/src/endpoints/mod.rs
rs/ic-management-backend/src/endpoints/subnet.rs
rs/ic-management-backend/src/health.rs
rs/ic-management-backend/src/lazy_registry.rs
rs/ic-management-backend/src/registry.rs
rs/ic-management-backend/src/release.rs
rs/ic-management-backend/src/subnets.rs
rs/ic-management-types/Cargo.toml
rs/np-notifications/Cargo.toml
rs/np-notifications/src/nodes_status.rs

- **Add a link to the forum thread for the update-authorized-subnets proposal**
- **feat(cli): Use IndexMap instead of BTreeMap where possible, to keep the ordering**

feat(cli): Use IndexMap instead of BTreeMap where possible, to keep the ordering

---

rs/cli/src/commands/subnet/resize.rs
rs/cli/src/runner.rs
rs/cli/src/subnet_manager.rs

In addition to the improved summary:
Changes:
- arguments --add and --remove now include default values, allowing users to omit these values if not needed.
- the `id` field has an alias of `subnet-id` for improved readability.
Refactor: the `execute` method now uses the `subnet_manager` to resize the subnet and proposes the subnet change using the `runner`. This makes the `resize` functionality very similar to the `replace` functionality, so more code can be shared between the two.

feat(dre): Improve the summary of the subnet resize NNS proposals

---

rs/ic-management-backend/src/registry.rs

Instead just print the error message and continue.
The dashboard is not actively used anymore to get an overview of rollouts, so no need to crash important operations due to missing git revs.

fix(backend): Do not crash the backend if some git revisions cannot be found

---

rs/cli/src/commands/registry.rs

The node type information is not yet associated with node records in the registry.
There is an ongoing effort to rectify that, and to achieve that we need an accurate estimate of the node types based on the information available in the node operator record: rewardable_nodes.
What the code does is:
- iterate over all nodes, and
- for each node fetch the node operator
- count the number of rewardable nodes of in each type (implementation detail: this is done by subtracting the rewardable nodes count)
- estimate the node type based on the next available rewardable_nodes entry (not yet assigned to some other node record)
Again, this is only an estimate, and the correct information will be added to the registry in the future by the NNS team. At that point, we'll want to adjust the code.
Node …

feat(dre): Provide an estimate of node types in the `dre registry`

---

rs/cli/src/commands/mod.rs
rs/cli/src/ctx.rs
rs/ic-management-backend/src/lazy_registry.rs

"No sync" is the term we use only for syncing with registry canister. This flag is intended to have a broader use which covers the case of when public dashboard is offline as well.

refactor(dre): renaming to `no_sync` to `offline` for clarity

---

Cargo.Bazel.lock
Cargo.lock
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics-frontend/src/components/NodeProviderRewards.tsx
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics-frontend/src/components/NodeRewardsChart.tsx
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics-frontend/src/components/Widgets.tsx
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics-frontend/src/utils/utils.tsx
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics-types/src/types.rs
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics/Cargo.toml
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics/src/chrono_utils.rs
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics/src/lib.rs
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics/src/metrics_manager.rs
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics/src/rewards_manager.rs
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics/src/stable_memory.rs
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics/trustworthy-node-metrics.did

- Include unassigned days in node rewards algo
- Include logging for unassigned days
- Fixed test for it
- Added expected rewards per node provider

Add unassigned nodes reward computation

---

Cargo.Bazel.lock
Cargo.lock
cordoned_features.yaml
deny.toml
rs/cli/Cargo.toml
rs/cli/src/commands/mod.rs
rs/cli/src/commands/subnet/replace.rs
rs/cli/src/commands/subnet/resize.rs
rs/cli/src/cordoned_feature_fetcher.rs
rs/cli/src/ctx.rs
rs/cli/src/lib.rs
rs/cli/src/main.rs
rs/cli/src/operations/hostos_rollout.rs
rs/cli/src/runner.rs
rs/cli/src/subnet_manager.rs
rs/cli/src/unit_tests/ctx_init.rs
rs/cli/src/unit_tests/mod.rs
rs/cli/src/unit_tests/replace.rs
rs/cli/src/unit_tests/update_unassigned_nodes.rs
rs/cli/src/unit_tests/version.rs
rs/decentralization/src/nakamoto/mod.rs
rs/decentralization/src/network.rs
rs/decentralization/src/subnets.rs
rs/ic-management-backend/src/health.rs

This PR adds the ability to cordon features by adding entries to the new `cordoned_features.yaml` file. Currently it will exclude from the pool of available nodes all the nodes with the cordoned feature. It will not attempt to remove all healthy nodes (in the subnet) that have said feature, it will just prevent entering of the new nodes with those features.
When removing nodes from the subnet and when they are added back to the available pool, if the removed node contains cordoned features it will not be added to the available pool. It means that some of the nodes containing cordoned features _could_ be removed if the business rules are met.

feat: cordon features

---

rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics-frontend/src/App.tsx
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics-frontend/src/components/Drawer.tsx
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics/src/rewards_manager.rs

- Add Node Provider rewards computation algorithm based on avg. rewards and coefficients for `type3*` nodes, all other types rewarded without coefficient
- Added reduction for underperforming nodes
- Display computation log in the dashboard
- Display NP names instead of ids in dropdown menu

Add NP rewards computation algorithm

---

rs/decentralization/src/nakamoto/mod.rs
rs/decentralization/src/network.rs

The previous replacement of city with the country in the EU countries had unintended consequences on the decentralization calculations. To avoid further issues, this pull request reverts the code back to its original state, where EU countries are handled separately and EU is not included in the calculations.

Revert EU country handling in decentralization code

---

release-index.yaml

Reverted three commits on top of the base release to solve the problem of high utilization in subnet `fuqsr`.

rc--2024-10-03_01-30-canister-overhead-hotfix

---

release-controller/release_index_loader.py
release-controller/test_release_index_loader.py
rs/cli/src/runner.rs

Since https://github.com/dfinity/ic/pull/2148, repro-check.sh accepts a `--guestos` argument to verify build reproducibility of GuestOS only.
Since build reproducibility of HostOS and SetupOS isn't of critical importance for GuestOS proposals, let's omit the checks of those two in the version elect proposals.

chore(release): Pass --guestos to repro-check.sh in proposal summaries

---

rs/cli/src/commands/registry.rs

Rust acts the same way the following would: `cat ... | sort | uniq`

fix: duplicate entries in `node_providers`

---

release-index.yaml

There are still two versions awaiting qualification. Until then the PR will be left as a draft

chore: release `rc--2024-10-31_03-09`

---

release-index.yaml

The qualification had issues and there were more reverts.

fix: using correct version for the ubuntu20.04 release

---

Cargo.Bazel.lock
Cargo.lock
Cargo.toml
rs/cli/Cargo.toml
rs/cli/src/auth.rs
rs/cli/src/commands/mod.rs
rs/cli/src/unit_tests/ctx_init.rs

Eliminate the clio dependency and update the handling of private_key_pem in AuthOpts to use a String instead of InputPath. This change simplifies the code and improves the management of private key paths.
```
error[E0599]: the method `value_parser` exists for reference `&&&&&&_infer_ValueParser_for<InputPath>`, but its trait bounds were not satisfied
--> rs/cli/src/commands/mod.rs:99:5
|
99   |     /// Path to private key file (in PEM format)
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ method cannot be called on `&&&&&&_infer_ValueParser_for<InputPath>` due to unsatisfied trait bounds
|
::: /home/sat/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.5.20/src/builder/value_parser.rs:2423:1
|
2423 | pub struct _infer_ValueParser_for<T>(std::marker::PhantomData<T>); …
```

refactor: remove clio dependency to fix compilation issues

---

release-controller/publish_notes.py
release-controller/test_publish_notes.py

This PR modifies the step before creating a PR on our repository for reviewing changes. Previously the only criteria we checked was if all the teams reviewed the notes (by crossing their name out). With this PR we will check how many changes are publishable. 
Change is publishable if its not: 
* Manually excluded by developers
* Automatically excluded by release controller

feat: ensure that there are some publishable changes in release notes

---

rs/decentralization/src/lib.rs
rs/decentralization/src/network.rs
rs/ic-management-backend/src/endpoints/query_decentralization.rs
rs/ic-management-backend/src/subnets.rs

Introduce logging for business rules checks in subnet change responses, to clarify reasons a subnet might have non-compliant (having penalties).

feat(dre): Add business rules logging to subnet change responses

---

rs/cli/src/commands/registry.rs

Introduce a new field to the NodeOperator struct to track the number of nodes associated with a specific operator in the registry.

feat(dre,registry): add nodes_in_registry field to NodeOperator

---

Cargo.Bazel.lock
Cargo.lock
rs/cli/src/commands/registry.rs
rs/cli/src/operations/hostos_rollout.rs
rs/cli/src/qualification/run_workload_test.rs
rs/cli/src/qualification/run_xnet_test.rs
rs/cli/src/qualification/upgrade_subnets.rs
rs/cli/src/runner.rs
rs/cli/src/subnet_manager.rs
rs/cli/src/unit_tests/replace.rs
rs/decentralization/src/lib.rs
rs/decentralization/src/nakamoto/mod.rs
rs/decentralization/src/network.rs
rs/decentralization/src/subnets.rs
rs/ic-management-backend/src/endpoints/query_decentralization.rs
rs/ic-management-backend/src/lazy_registry.rs
rs/ic-management-backend/src/registry.rs
rs/ic-management-backend/src/subnets.rs
rs/ic-management-types/Cargo.toml
rs/ic-management-types/src/lib.rs

This should make it easier to understand and write code in the future.
No functional changes are expected in this PR.

refactor(dre): replace "decentralized" node with backend node

---

rs/cli/src/commands/subnet/replace.rs
rs/cli/src/runner.rs
rs/cli/src/subnet_manager.rs
rs/cli/src/unit_tests/replace.rs
rs/decentralization/src/lib.rs
rs/decentralization/src/nakamoto/mod.rs
rs/decentralization/src/network.rs
rs/decentralization/src/network_tests.rs
rs/ic-management-types/src/lib.rs

From all nodes that result in the same decentralization (Nakamoto coefficients) prefer those nodes that come from less used node operators. This should balance out the node operator utilization, and overall result in better decentralization across all subnets.

feat(decentralization): from nodes with same dec. prefer those from less used operators

---

.github/workflows/main.yaml
.github/workflows/pull-request-update.yaml
.github/workflows/update-dependencies.yaml

This is part of a larger effort to remove the need for PATs generated by service accounts and use GitHub apps instead.

chore(IDX): replace PAT with GitHub App

---

rs/cli/src/commands/mod.rs
rs/cli/src/commands/subnet/replace.rs
rs/cli/src/ctx.rs
rs/cli/src/discourse_client.rs
rs/cli/src/ic_admin.rs
rs/cli/src/lib.rs
rs/cli/src/main.rs
rs/cli/src/unit_tests/ctx_init.rs
rs/cli/src/unit_tests/update_unassigned_nodes.rs
rs/cli/src/unit_tests/version.rs

This pull request adds an initial discourse client. The discourse client takes care of low level calls and high level coordination should be implemented into a Trait which exposes a clear api.
At the moment only the `subnet replace` command is changed to use the discourse api. If this was to be merged, further code changes for relevant proposal types would be added in a separate PR.
Still thinking about how to reliably test it.

feat(dre): Discourse client for automatic forum post management around proposals.

---

rs/cli/src/commands/mod.rs
rs/cli/src/commands/subnet/replace.rs
rs/cli/src/ctx.rs
rs/cli/src/discourse_client.rs
rs/cli/src/ic_admin.rs
rs/cli/src/unit_tests/ctx_init.rs

If discourse client is failing for some reason, one should be able to still use the tool.
This PR adds two ways:
1. Skip the creation of the forum link all together with `--discourse-skip-post-creation`
2. The tool will print out a couple of warning messages saying that it failed to create a topic and it will prompt user for the forum post link after he manually created it.
Example of manual creation request:
<details>
~~~bash
./target/debug/dre --discourse-api-key some --discourse-api-user some --discourse-api-url "https://we.com"  subnet replace --nodes 5ttnf-xhdip-7e2uw-iuikh-5dlli-r6jdc-nxjp7-bjumm-5usid-rpiqn-jqe --no-heal --motivation "testing"
2024-11-22T10:25:30.134Z INFO  dre > Running version 0.5.6-8f4aeb7f-dirty
2024-11-22T10:25:30.178Z INFO  dre::store > Using local registry …

feat: adding workarounds if post creation fails.

---

BUILD.bazel
rs/cli/BUILD.bazel
rs/cli/src/commands/mod.rs
rs/cli/src/cordoned_feature_fetcher.rs
rs/cli/src/ctx.rs
rs/cli/src/runner.rs
rs/cli/src/store.rs
rs/cli/src/unit_tests/cordoned_feature_fetcher.rs
rs/cli/src/unit_tests/replace.rs
rs/decentralization/src/network.rs

Previous implementation was using the local file for cordoned features *only if* --offline was provided. That means that the entire dre tool had to be forced to go offline.
With this change, one can simply provide `--cordoned-features-file <file>` on the CLI, and the local file will override the github version

feat: update cordoned features handling and support for local file

---

rs/cli/src/commands/update_authorized_subnets.rs
rs/ic-canisters/src/cycles_minting.rs
rs/ic-canisters/src/lib.rs

The new summary will have a table that looks like the following:
| Subnet id | Public | Description |
| --------- | ------ | ----------- |
| 2fq7c-slacv-26cgz-vzbx2-2jrcs-5edph-i5s2j-tck77-c3rlz-iobzx-mqe | false | Subnet has more than 60000 canisters |
| 3hhby-wmtmw-umt4t-7ieyg-bbiig-xiylg-sblrt-voxgt-bqckd-a75bf-rqe | ~~true~~ ⇒ false | Subnet has more than 300 GiB state size |
| 4ecnw-byqwz-dtgss-ua2mh-pfvs7-c3lct-gtf4e-hnu75-j7eek-iifqm-sqe | true |  |
| 4zbus-z2bmt-ilreg-xakz4-6tyre-hsqj4-slb4g-zjwqo-snjcc-iqphi-3qe | false | Verified App subnet |
| 5kdm2-62fc6-fwnja-hutkz-ycsnm-4z33i-woh43-4cenu-ev7mi-gii6t-4ae | false | Verified App subnet |
| 6pbhf-qzpdk-kuqbr-pklfa-5ehhf-jfjps-zsj6q-57nrl-kzhpd-mu7hc-vae | ~~true~~ ⇒ false | Subnet has more than 300 GiB state size |
| …

chore: integrating call cmc to show diff

---

cordoned_features.yaml

The previous change was a misunderstanding or misreading, it was not DL1 but PL1 that the NP is selling off.

chore: Add the PL1 DC into the cordoned DCs

---

Cargo.lock
rs/cli/src/auth.rs
rs/ic-canisters/src/parallel_hardware_identity.rs

* Tighten the interface between the ParallelHardwareIdentity module and its users.
* Simplify error handling when collecting the PIN.
* Make PIN prompt robust against failures of the system keyring (PIN may not be saved, but at least the tool works with manual prompting).
* Protect HSM from locking itself if the PIN is at its last try -- skip retrieving the PIN from the keyring, and prohibit the use of environment variables to supply the PIN, preferring to prompt the user for a PIN instead (or let the user cancel).

HSM handling improvements.

---

.github/workflows/build/action.yaml
.github/workflows/main.yaml

An alternative implementation similar to https://github.com/dfinity/dre/pull/1135 would also work, but that would approximately double the load on the CI.
The change from this PR doesn't increase the load, although admitedly it's not as clean as #1135

fix(ci): use GitHub App token to trigger CI actions

---

rs/cli/src/discourse_client.rs
rs/cli/src/runner.rs

In particular: collapse the proposal summary, to reduce the forum post length.
Here is how the post looks like
And expanded:

fix: update discourse forum posts contents for subnet proposals

---

rs/cli/src/auth.rs
rs/cli/src/commands/api_boundary_nodes/mod.rs
rs/cli/src/commands/hostos/mod.rs
rs/cli/src/commands/mod.rs
rs/cli/src/commands/neuron/mod.rs
rs/cli/src/commands/nodes/mod.rs
rs/cli/src/commands/proposals/mod.rs
rs/cli/src/commands/qualify/mod.rs
rs/cli/src/commands/subnet/deploy.rs
rs/cli/src/commands/subnet/mod.rs
rs/cli/src/commands/version/mod.rs
rs/cli/src/commands/version/revise/mod.rs
rs/cli/src/ctx.rs
rs/cli/src/unit_tests/ctx_init.rs

There are some proposals that we would like to _automatically_ submit with correct neuron that is not the default neuron (Like subnet version upgrade proposals). This PR adds the possibility to add an override on a command level that will be used only if no other auth opts are specified.
This PR also includes removing of some boiler plate code as well and turns it into a macro

feat: Adding possibility to override neurons per command

---

rs/cli/src/commands/version/revise/guest_os.rs
rs/cli/src/commands/version/revise/host_os.rs
rs/cli/src/runner.rs
rs/cli/src/unit_tests/version.rs

Updated GuestOs and HostOs structs to make release_tag an Option<String>. Adjusted relevant functions to handle the new optional release_tag properly.

feature: Change release_tag field to be optional

---

release-controller/git_repo.py
scripts/host-os-release-notes.py

The changes in this PR involve the removal of the suppression of `stdout` and `stderr` for various Git commands in the `GitRepo` class and the `host-os-release-notes.py` script. This includes commands such as `checkout`, `fetch`, and `reset`, which now will output their standard messages and errors to the console.
Impact:
- Improved visibility of Git command outputs, aiding in debugging and understanding of the operations being performed by the application.
- Reduced potential difficulties in diagnosing issues, as the immediate feedback from Git operations is now available.

fix(release-controller): remove suppression of stdout and stderr in Git commands

---

rs/cli/src/commands/update_authorized_subnets.rs

After recent development the limits adjusted. During discussion it was noted that state size criteria technically could be removed all together but we opted to keep it until further CMC development takes place.
Full discussion in [this thread](https://dfinity.slack.com/archives/C01DB8MQ5M1/p1736151170753039).

chore(dre): New defaults for state size when updating authorized subnets

---

.github/repo_policies/BOT_APPROVED_FILES

Needed for the repo policy check. That is why the CI is failing on pr #1185

chore: adding `BOT_APPROVED_FILES`

---

cliff.toml

Just so that we remove commits [like](https://github.com/dfinity/dre/pull/1206) this from the changelog

fix: removing the release from the new release changelog

---

docs/chat/icp-support.md
mkdocs.yml

We decided to not go with this route. This PR cleans up the remains of icp support chatbot

chore: removing chat integration from docs

---

.github/workflows/update-dependencies.yaml

There is a filter in `cliff.toml` that will skip all conventional commits that start with `chore(deps)` and the aim of this PR is to use that to skip automatic dependency bumps. 
An argument can be made that the users of our rust libraries would maybe love to know what are the upgraded versions of the libraries but I doubt it is useful in changelog and it should be kept as slim as possible.

fix: don't include automatic upgrades into changelog for `dre`

---

cliff.toml
release-controller/publish_notes.py

This PR will filter all `chore(release)` commits from `dre` tool changelog so that we keep it small

chore: skipping all `chore(release)` commits from dre changelog

---

rs/cli/src/commands/neuron/balance.rs

**Field Renaming**: Renamed `neuron` field to `neuron_override` in the `Balance` struct, in order to fix:
```
❯ dre neuron balance
[...]
thread 'main' panicked at external/crate_index_dre__clap_builder-4.5.22/src/builder/debug_asserts.rs:442:80:
long option names must be unique, but '--neuron' is in use by both 'neuron_id' and 'neuron'
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

refactor(cli): rename neuron input field

---

rs/cli/src/commands/network.rs

- Extend `Network` command to check for open `AddApiBoundaryNodes` proposals in the `ProposeCommand`.
Fixes: https://dfinity.slack.com/archives/C02NJPNSLM6/p1737140872700689?thread_ts=1737135696.312359&cid=C02NJPNSLM6

fix: check for open AddApiBoundaryNodes proposals in network command

---

rs/ic-canisters/src/parallel_hardware_identity.rs

Correct a logic bug that causes a panic when detecting HSM devices, if a device which is not a NitroKey is plugged as well.

Fix HSM detection issue

---

rs/cli/src/commands/neuron/balance.rs
rs/cli/src/ctx.rs

- **Removed Neuron Override in Balance Command**: Eliminated the unnecessary `neuron_override` field from the `Balance` struct.

refactor(cli): streamline neuron balance execution

---

rs/cli/src/commands/firewall.rs
rs/cli/src/qualification/ensure_blessed_versions.rs
rs/cli/src/qualification/retire_blessed_versions.rs

- **cli.commands:** Add `forum_post_link` and `motivation` to `ProposeOptions` in `Firewall` command.
- **cli.qualification:** Add `forum_post_link` to `ProposeOptions` in `EnsureBlessedRevisions` and `RetireBlessedVersions`.
- Updated `firewall.rs` to include `forum_post_link` and set `motivation` to `None`.
- Updated `ensure_blessed_versions.rs` to include `forum_post_link` and set `motivation` to `None`.
- Updated `retire_blessed_versions.rs` to include `forum_post_link` using the context's DRE link.

feat(cli): add forum post link to proposal options

---

rs/cli/src/commands/mod.rs
rs/cli/src/ctx.rs
rs/cli/src/unit_tests/ctx_init.rs

Previously the tool would error out if nothing is provided.
With this the tool will use placeholder key and user which will fail to create posts but the user will be prompted to create them manually and provide the links.

fix(dre): dont require discourse secrets for actions

---

cordoned_features.yaml

Offboarded the second rack of nodes in the mb1 data center (DC) as part of a scheduled operation after 48 months.
- Added multiple entries corresponding to node IDs in the `cordoned_features.yaml` file.
- Each node ID is documented with an explanation and a reference to the proposal discussion URL for offboarding operations.

feat: offboard nodes from mb1 DC

---

rs/cli/src/commands/network.rs
rs/cli/src/runner.rs
rs/decentralization/src/nakamoto/mod.rs
rs/decentralization/src/network.rs

- Consolidated network healing and cordoned nodes removal into a single process.
- Extended `network_heal` functionality to handle both unhealthy and cordoned node replacement. This should result in fewer proposals in some cases, and overall produce better decentralization results.
- Removed standalone `network_remove_cordoned_nodes` function and refactored logic accordingly.
Example proposal submitted with the new code: https://dashboard.internetcomputer.org/proposal/134983

refactor: integrate cordoned node removal into network healing

---

rs/cli/src/commands/governance/mod.rs
rs/cli/src/commands/governance/propose/mod.rs
rs/cli/src/commands/governance/propose/motion.rs
rs/cli/src/commands/mod.rs
rs/ic-canisters/src/governance.rs

User must specify a `--proposal-url` for discussion of the proposal, a single non-option argument specifying a file (`-` for stdin) to supply a proposal summary, and optionally a `--title` / a `--motion-text` / a `-motion-text-file`.
If not run with `--dry-run`, this command will not ask you for confirmation.  This is compatible with the way DRE does things (e.g. `dre vote`), and breaks away from the convention of `ic-admin`.  Run it with `--dry-run` and verify the proposal payload is what you meant it to be, before submitting.
Parameters as per right now:

Implement the motion feature in DRE.

---

dashboard/packages/app/src/components/subnets/AvailableNodes.tsx
dashboard/packages/app/src/components/subnets/types.tsx
rs/cli/src/commands/registry.rs
rs/cli/src/operations/hostos_rollout.rs
rs/decentralization/test_data/available-nodes.json
rs/decentralization/test_data/subnet-uzr34.json
rs/ic-management-backend/src/lazy_registry.rs
rs/ic-management-backend/src/registry.rs
rs/ic-management-types/src/lib.rs

- Introduced `NodeOperatorComputed` struct to group computed fields within `NodeOperator`.
- Updated fields under the `computed` struct: `nodes_health`, `total_up_nodes`, `rewards_correct`, `node_allowance_remaining`, `node_allowance_total`, `nodes_in_subnets`, and `nodes_in_registry`.
- Renamed `allowance` to `node_allowance` consistently across the codebase.
- Updated logic in `Registry` for better encapsulation of computed properties, including calculation of `node_allowance_total` and condition checks involving `total_up_nodes`.
- Updated tests and affected modules to reflect struct and field changes.

refactor: encapsulate NodeOperator computed fields

---

docs/contributing.md
docs/index.md
docs/nns-motion-proposals.md
mkdocs.yml

**Contributing Guide Updates:**
- Reorganized the contributing guide for better clarity and flow.
- Enhanced sections on setting up the development environment and troubleshooting.
- Included detailed instructions for environment setup, focusing on Python (Rye), Rust, Node.js, and Yarn.
- Added pre-commit hooks and expanded IDE configuration instructions.
**Project Overview and Documentation:**
- Elaborated on DRE components and introduced a structured introduction in the index.
- Enumerated DRE features, structure, and resources to facilitate onboarding.
- Consolidated links to key resources and documentation updates, enhancing navigability.
**New NNS Motion Proposals Guide:**
- Added a detailed guide on submitting NNS motion proposals explicitly outlining prerequisites, forum …

docs: Revise contribution and documentation overview

---

mkdocs.yml

We actually can't track cookies since we serve pages on GH.

chore: remove cookie consent configuration

---

docs/contributing.md

- **Added Badges:**
- Contributions Welcome
- Python Manager (Rye)
- Pre-commit Enabled
- **Updated Table of Contents:**
- Added sections for Code Style Guidelines, Pull Request Process, Common Issues, and Getting Help.
- **Added Code Style Guidelines:**
- Included specific guidelines for Python (PEP 8), Rust, and JavaScript/TypeScript.
- **Defined Development Workflow:**
- Detailed steps for contributing, including forking, branch creation, development setup, and pull request creation.
- **Outlined Pull Request Process:**
- Steps for submitting a PR, including testing, documentation updating, linking issues, and review actions.
- **Expanded Common Issues Section:**
- Added detailed steps for handling permission errors, node version mismatches, and Bazel cache issues.
- **Enhanced Getting …

docs: enhance contributing guidelines

---

rs/ic-observability/multiservice-discovery/src/definition.rs
rs/ic-observability/multiservice-discovery/src/main.rs

In case of testnets (be it farm testnets or new k8s testnets) we will be notified upon testnet creation but not on test removal. This PR aims to add the possibility for MSD to know which testnets are no longer active and remove them for the exported targets and scraping.

feat(msd): adding possibility to remove stale targets

---

rs/ic-observability/multiservice-discovery/src/definition.rs

A very niece bug can happen when the same directory is reused with a different network. If the old network and the new network have the same height, our discovery will not sync old stuff but will assume it is the latest version with false values (coming from a previous network with the same name)

chore(msd): deleting directory once the network is garbage collected

---

rs/cli/src/commands/registry.rs
rs/cli/src/ctx.rs
rs/cli/src/store.rs
rs/ic-management-backend/src/lazy_registry.rs

This PR adds the possibility to list the registry at specific height. Default behavior remains listing the latest height.
Example usage:
```bash
dre registry --height 41890
```

feat: listing registry at specific height

---

cordoned_features.yaml

- Add node_operator entry with value `wmrev-cdq34-iqwdm-oeaak-f6kch-s4axw-ojbhe-yuolf-bazh4-rjdty-oae` for freeing up nodes from JV1 for HSM-less redeployment.
- Add node_operator entry with value `codio-e5e6p-ol6sn-o3mgw-r7v5p-4jmch-a7exl-7pifz-cw4gn-ah47y-6ae` for freeing up nodes from AW1 for HSM-less redeployment.
- Add data_center entry with value `an1` for freeing up nodes from AN1 data center for HSM-less redeployment.

feat: update cordoned features for redeployment

---

rs/cli/src/commands/subnet/replace.rs
rs/cli/src/commands/subnet/resize.rs
rs/cli/src/runner.rs

The `Runner::propose_subnet_change` method now accepts a reference to the `SubnetChangeResponse` instead of cloning it. This refactoring simplifies the method call and improves performance by avoiding unnecessary copies.
11 lines of code deleted too.

Refactor proposal generation to accept runner change response directly

---

rs/cli/src/commands/registry.rs
rs/ic-management-backend/src/lazy_registry.rs

For low heights it is possible that some structs will have missing data due to registry not having them at low heights.

fix: not panicing for unknown operators because of low heights

---

rs/cli/src/forum/impls.rs

- Implemented a retry mechanism for sending requests to the Discourse API to handle `TOO_MANY_REQUESTS` errors by retrying with exponential backoff.
- Modified existing request logic to encapsulate retry logic using a `for` loop.
- Updated error handling to include retries upon request failures, with a max retry count of 5 and incremental sleep before each retry.
- Included logging for rate limiting warnings and retry attempts.
- Eliminated old match structure for direct request handling, replacing it with retry-inclusive logic.
- Added unreachable!() statement to ensure code paths are handled explicitly.

feat: implement retry mechanism for Discourse API requests

---

release-controller/dre_cli.py

Moved the "--yes" flag after other arguments to comply with the fact that mode of operation arguments are part of the subcommand now.

Reorder command line arguments in the DRE invocation.

---

release-controller/dre_cli.py

Changed the binary name from 'old-dre' to 'dre'.
This update ensures that the correct executable is used for DRE operations.

Update DRE CLI binary name, fixing brown paper bug.

---

release-controller/dre_cli.py
release-controller/reconciler.py

Simplified propose command execution by removing redundant checks for obsolete ways of proposing GuestOS elections, and improving argument construction.
Updated reconciliation error logging to use exception for better traceability. We were swallowing the exception instead of printing it.

Refactor DRE CLI propose command handling.

---

rs/cli/src/commands/api_boundary_nodes/add.rs
rs/cli/src/commands/api_boundary_nodes/remove.rs
rs/cli/src/commands/api_boundary_nodes/update.rs
rs/cli/src/commands/firewall.rs
rs/cli/src/commands/governance/propose/motion.rs
rs/cli/src/commands/hostos/rollout.rs
rs/cli/src/commands/hostos/rollout_from_node_group.rs
rs/cli/src/commands/network.rs
rs/cli/src/commands/nodes/remove.rs
rs/cli/src/commands/propose.rs
rs/cli/src/commands/subnet/create.rs
rs/cli/src/commands/subnet/deploy.rs
rs/cli/src/commands/subnet/replace.rs
rs/cli/src/commands/subnet/rescue.rs
rs/cli/src/commands/subnet/resize.rs
rs/cli/src/commands/update_authorized_subnets.rs
rs/cli/src/commands/update_unassigned_nodes.rs
rs/cli/src/commands/version/revise/guest_os.rs
rs/cli/src/commands/version/revise/host_os.rs
rs/cli/src/proposal_executors.rs
rs/cli/src/submitter.rs

This PR refactors proposal submission handling on the Submitter to return `Option<ProposalResponseWithId>`.
With that refactor done, we can make a change across multiple CLI subcommands to ensure that the result of a successful proposal execution (as opposed to just simulation) is printed.
*Key changes:*
- Updated the `Submitter::propose` method signature to return `anyhow::Result<Option<ProposalResponseWithId>>`.
- Added detailed handling and logging for the proposal URL addition process in case of success or failure.
- Ensured CLI commands properly handle and display the proposal ID if returned by the submission process.
This adds compatibility with `ic-admin` to all proposals submitted with DRE, which in turn will be used to fix an issue in release controller.

Print proposal ID when a proposal is issued.

---

release-controller/README.md
release-controller/reconciler.py
release-controller/reconciler_state.py
release-controller/tests/test_reconciler.py
release-controller/util.py

This PR updates the `ReconcilerState` class to use an in-memory dictionary for state storage instead of file operations. This change simplifies initialization and eliminates file system interactions, improving performance and reliability.
The main effect of this change is to make the reconciler retry proposals that formerly failed to be submitted *immediately after restart*, rather than (as is right now) waiting for a configured retry duration.
The configured retry duration is still respected during the execution of the reconciler.

Keep track of proposal state, used by reconciler, only in RAM.

---

release-controller/BUILD.bazel
release-controller/dre_cli.py
release-controller/dryrun.py
release-controller/reconciler.py

Our release controller can be run with `bazel run` (an activity frequently engaged in during local testing).  When this takes place, currently and by default the release controller will attempt to use whatever `dre` binary is in the user's `$PATH`.
This obviously fails when there's no such binary.
To address this, and to ensure that the release controller is running with an up-to-date version of `dre`, this change makes Bazel build the `dre` binary before starting the release controller, and then makes the release controller use the Bazel-built `dre` program, but only when running under Bazel.
This commit introduces support for an optional `cli_path` parameter in the `DRECli` class constructor, allowing users to specify a custom path to the `dre` CLI executable. This change is also useful …

Use Bazel to build DRE CLI when running release controller through Bazel

---

pyproject.toml
release-controller/BUILD.bazel
release-controller/reconciler.py
requirements-dev.lock

Added prometheus-client to dependencies and implemented metrics for cycle success and start timestamps. Updated the telemetry port argument and added Prometheus server initialization.
There is a command line option to set the port for telemetry.  In its default value, it is 9467.
To follow: alerts based on collected telemetry as well as runbooks.

feat: success/failure telemetry in release controller reconciler

---

rs/decentralization/src/nakamoto/mod.rs
rs/decentralization/src/network.rs

- Utilize `feature_value_counts` for penalty determination instead of `feature_value_counts_max`, so that ALL instances of values above the maximum allowed are penalized. This should result in more correct penalty calculations in case there are multiple violations.

fix(decentralization): improve node penalty calculations

---

rs/ic-management-backend/src/lazy_registry.rs

- Standardized variable naming by renaming `principal` to `operator_principal` for clarity.
- Introduced `provider_principal` variable to handle node provider principal IDs.
- Ensured consistent use of `operator_principal` in log messages.
- Updated closure logic to manage provider details using newly named variables.

fix: use provider principal instead of operator in LazyRegistry

---

release-controller/BUILD.bazel
release-controller/dre_cli.py
release-controller/dryrun.py
release-controller/reconciler.py
release-controller/util.py
tools/python/py_oci_image.bzl

Binary is already included as data dependency.
Additionally, updated `util.py` to include a logger for debugging binary resolution.

fix: avoid including DRE binary twice in the release controller container

---

docs/nns-motion-proposals.md

- **DRE Team Motion Proposal Workflow**: 
- Steps for preparing and submitting motion proposals detailed in a new section, `Motion Proposal Workflow for DRE Team`.
- Includes instructions for creating proposal content, submitting through DRE CLI, and updating proposal filenames.
- Clarification on finalizing changes and maintaining records through a structured PR process.
- **References**:
- Corrected link to DRE CLI Documentation from GitHub to the GitHub Pages.

docs: add motion proposal workflow for DRE Team

---

rs/decentralization/src/network.rs

- **Refactor Subnet Identification:**
- Consolidate subnet identification logic using `is_european_subnet` and `is_nns_subnet` to enhance clarity and reduce redundancy.
- **Introduce allowances for DFINITY on the NNS subnet:**
- Introduce allowances for DFINITY to maintain up to 3 nodes on the NNS subnet, in line with the adopted https://dashboard.internetcomputer.org/proposal/135700

feat(decentralization): Adjust business rules calculation for proposal 135700

---

rs/decentralization/src/network/healing.rs

- **Re-sort Subnets:** Implemented sorting of `subnets_to_fix` based on priority to ensure the most critical subnets are addressed first.

fix(healing): sort subnets by priority

---

rs/cli/src/commands/propose.rs
rs/cli/src/confirm.rs

- **Help Handling**: Implement manual '--help' handling in `Propose` struct, disabling automatic flag parsing to manage propose subcommands.
- **Dry-Run Mode**: Enable dry-run mode when '--help' is present to bypass interactive prompts.

feat(cli): refine '--help' handling in propose command

---

rs/cli/src/forum/mod.rs
rs/cli/src/governance.rs
rs/cli/src/ic_admin.rs
rs/cli/src/proposal_executors.rs
rs/cli/src/submitter.rs
rs/cli/src/unit_tests/update_unassigned_nodes.rs
rs/cli/src/unit_tests/version.rs

- **Forum Post Link Simulation**:
- Added `forum_post_link_for_simulation` method to `ForumParameters` to generate a link for simulation purposes.
- Updated `simulate` function implementations in `GovernanceCanisterProposalExecutor`, `ProposalExecutionViaGovernanceCanister`, and `IcAdmin` traits to include an optional forum post link description when simulating proposals.
- Modified functions to print the forum post link description during simulations for better traceability.
- **Unit Tests**:
- Adjusted unit tests to accommodate the additional forum post link parameter in proposal simulation.

feat(cli): support forum post link simulation

---

BUILD.bazel
pyproject.toml
release-controller/BUILD.bazel
release-controller/README.md
release-controller/commit_annotator.py
release-controller/git_repo.py
release-controller/reconciler.py
release-controller/release_notes.py
release-controller/tests/runner.py
release-controller/tests/test_commit_annotator.py
release-controller/util.py

This commit renames the `commit_annotator` binary and associated Python script to `commit-annotator`, adhering to naming conventions. It also adds a new tag (`typecheck`) for the `commit-annotator` binary which enables mypy type checking, which has been completed too.
Prometheus metrics server has been added (defaults to listening on port 9468).
Options were added to allow the commit annotator to run in a dry-run mode, locally annotating tags without saving them to disk, pulling them from the remote, or pushing them to the remote.  These changes allow for manual testing of the commit annotator without any credentials.
Conventional logging as well as loop time allow the annotator to run on a looser loop without spinning CPU uselessly between runs.

Clean up the commit annotator and add telemetry

---

docs/be-dr-dre.md
release-controller/git_repo.py

The first thing in this commit is to remove this message from the standard error:
```
error: no note found for object 7d4e057cbb17f4bf2a108d547402cb5e7bf3eacc.
```
which is unnnecessary.  I had even added the functionality to do this very thing into the `notes()` function before, but forgot to call it when it was appropriate.  The code does the right thing -- but it just looks ugly when doing it.
The second thing is the URL to the Jira ops board which should be fixed to exclude closed alerts because they are noise and should not be shown by default.  So we I it here.
I'll handle rollout of the annotator after this.

A twofer: fix ugly error message in annotator, and enhance docs.

---

rs/cli/src/subnet_manager.rs

- **Improved Clarity**: Modify log messages in `SubnetManager` to more clearly indicate node replacement based on health or optimization for decentralization.
- **Conditional Logging**: Implement conditional checking to log only if healthy nodes are identified for replacement, with a default motivation message when none is provided.

refactor: enhance node replacement logging in SubnetManager

---

release-controller/release_notes.py

Fixing the following issue:
```bash
IndexError: list index out of range
II:git_repo             — Updating repository in /root/.cache/git/github.com/dfinity/dre.git to latest origin/main
II:reconciler           — GuestOS versions active on subnets or unassigned nodes: 6e64281a8e0b4faa1d859f115fc138eee6e136f8, de6e339b323f59fc07b18c23f37c3cd2aa8ceb55, f6f5e0927d14886e4bd67f776ee889f31cec2364
II:reconciler           — Dealing with the following releases:
II:reconciler           — 1. rc--2025-03-20_03-11 (base)
II:reconciler           — 2. rc--2025-03-14_03-10 (base)
II:reconciler           — 3. rc--2025-03-06_03-10 (base, disable-best-effort-messaging)
II:reconciler           — 4. rc--2025-02-27_03-09 (base, disable-best-effort-messaging) …
```

fix: codeowners parsing

---

release-controller/commit_annotator.py
release-controller/reconciler.py

This commit adds a new Prometheus Gauge metric `last_cycle_end_timestamp_seconds` to track the UNIX timestamp of the last cycle that completed, so that we can reliably detect stalled conditions separately from failures.
A companion PR to reform the alerts is coming.

Add extra telemetry to allow distinguishing between failure states.

---

release-controller/release_notes.py

This commit updates the log level from info to debug for lines parsed from the CODEOWNERS file during the release notes generation process. This change may provide more detailed output for troubleshooting purposes, without affecting the primary functionality of the system.

Change log level of CODEOWNERS parsing to debug

---

.github/workflows/main.yaml
.github/workflows/update-k8s-deployments/action.yaml

Updated the GitHub workflow for updating k8s deployments.
- Renamed input from 'github_api_token' to 'push-token'.
- Added step to check out the k8s repository using the 'actions/checkout@v4' action.
- Updated the commit message and PR title to include component information.
- Implemented logic to update or create a pull request based on existing PRs.
I will shut off any possible rollout PRs created by this merge, as they will tno be necessary.

Update k8s deployments action to use push-token and create PR

---

release-controller/publish_notes.py
release-controller/tests/test_publish_notes.py

Additionally, we refactor logging of the `PublishNotesClient` class to include the version.

Log when release controller is waiting for a PR to be approved.

---

release-controller/reconciler.py
release-controller/tests/test_reconciler.py

This commit introduces phase tracking to the `Reconciler` class, allowing for more granular monitoring of the reconciliation process.
Each phase's success is now reported as a metric with labels. The PhaseCollector class manages phase transitions and failures, providing a structured way to track progress and issues during reconciliation cycles.
Companion PR for k8s:  https://github.com/dfinity-ops/k8s/pull/1005

feat(release-controller): add phase tracking and metrics

---

rs/cli/src/commands/upgrade.rs
rs/cli/src/main.rs

- **Refactor `Upgrade` Command:** Pass the current version (`curr_version`) as an explicit argument to `Upgrade::run` and `Upgrade::check` methods instead of using environment constants, for improved robustness.
- **Update Regex for Version Parsing:** Modified the regular expression in `check_latest_release` to accommodate version strings with `-v` prefixes, improving version specification accuracy and compatibility with git tags we use.
- **Log Enhancements:** Added logging to display the current and latest release versions during checks, increasing visibility for users.
In particular, previous code was always trying to upgrade when running from bazel due to special env variable handling, and it also wasn't able to handle versions like `0.6.0-v0.6.1` that would sometimes show up locally.

fix(cli): improve version upgrade checks

---

release-controller/commit_annotator.py

Updated the retry mechanism to use `stop_after_delay` of 3 minutes and `retry_if_exception_type` to limit retries to called process errors.
Removed logging of stderr as I'd like to see the output in real-time.

Retry behavior modifications for target determinator.

---

.github/workflows/check-modified-files-as-step/action.yaml
.github/workflows/main.yaml
.github/workflows/update-k8s-deployments/action.yaml

We use (and enhance) an existing trick to dynamically detect if the release controller needs to be updated, and if it does, then we run the necessary k8s action — a new, separately-invoked update-k8s-deployment action just for release controller and commit annotator.
In the existing update-k8s-deployment action invocation, we delete the release controller manifest files that were formerly edited by it.
Finally, the detection of changes between commits gains outputs to be used later on, which is easier to reason about than $GITHUB_ENV.

Release controller rollout cadence separate from other containers.

---

.github/workflows/check-modified-files-as-step/action.yaml
.github/workflows/main.yaml
.github/workflows/update-k8s-deployments/action.yaml

This update allows the action to handle space-separated lists of bash [[]]-compatible globs for path checking.
The modified script iterates over each file in the diff and checks it against each pattern, updating the output accordingly.
Globbing is turned off so the second-nested for loop won't get globbing to interfere with it.
As a further enhancement, now the workflow step checks for a diff range rather than just the last commit.  This makes the file modification checker work in many more and varied scenarios.
Finally, the Github workflow job summary feature looks like this:

Path checking for multiple glob patterns, and container rollout link in job summary.

---

.github/workflows/main.yaml

The 'Analyze Github event (temporary!)' step has been removed from the workflow. This was a temporary measure and is no longer needed since the pipeline has been fixed upon merge to main.

Remove temporary GitHub event analysis step

---

release-controller/commit_annotator.py

Prior to this PR, commit annotator was executing the bazel cquery and the target determination processes as sequential operations, each of which checked out a commit -- so every commit was checked out twice.
There is no implicit sequential dependency between the two, though.  Thus, this change makes commit annotator check out the commit only once, and make the target determination run in parallel with the bazel cquery, using the same local checkout in both cases.
This provides a measurable speedup primarily due to a reduction in disk access waste, but also due to the fact that now more cores can be active churning results.  A couple of seconds saved per commit means a couple minutes saved in anything beyond 30 commits to annotate.

Commit annotator: speed up target determination somewhat

---

.github/workflows/main.yaml

The baseline timings are 52 seconds for container pushes.  I hope this will shave 10 to 20 seconds with this concession.  Of course, we will only know for sure once something is merged to `main` that does not involve editing .github or Bazel files.
While it would probably be prudent to do target detection with Bazel, this detection is already in effect, so let's reuse it to speed up the process.

Speed up Bazel upload of containers when release controller has not been modified

---

Cargo.lock
rs/dre-canisters/node-provider-rewards/src/lib.rs
rs/dre-canisters/node-provider-rewards/src/metrics.rs
rs/dre-canisters/node-provider-rewards/src/metrics/tests.rs
rs/dre-canisters/node-provider-rewards/src/metrics_types.rs
rs/node-provider-rewards/src/execution_context/performance_multipliers_calculator/tests.rs
rs/node-provider-rewards/src/lib.rs
rs/node-provider-rewards/src/metrics.rs
rs/node-provider-rewards/src/reward_period.rs
rs/node-provider-rewards/src/tests.rs

Changes:
- Store `DailyNodeMetrics` directly instead of storing totals and compute daily metrics on query time
- Added tests for `DailyNodeMetrics` computation
- Decreased `instruction_counter` to 300K instructions for 1 month of metrics
TODO:
- Go through the NPR lib to decrease `instruction_counter` also there (currently 2.5B instructions used)

NPR Canister: Store DailyNodeMetrics directly

---

release-controller/prometheus.py
release-controller/reconciler.py
release-controller/util.py

1. In the log, note the oldest active release.
2. Fix an issue that impacted `bazel run` where the code was forgetting to return an environment variable.
3. Add state to the reconciler such that proposals that (1) have forum post updated (2) have proposal are not processed in the next loop.
4. Reform the active versions query to ensure that only versions with more than 10 nodes over the last hour are considered active by the reconciler.  This addresses a problem we found in production: a very old version appeared in the list of active versions (according to the old query), causing the reconciler to attempt to go back many months and process those releases, which it can't because there's a limit to how far back we can query for proposals.

Improvements to release controller reconciler

---

release-controller/release_index_loader.py
release-controller/tests/test_release_index_loader.py
rs/cli/src/runner.rs

- Update the IC-OS disk image verification instructions by replacing the shell script method with a direct curl and python execution.

chore: update IC-OS verification instructions to use the new repro-check

---

.github/workflows/main.yaml
.github/workflows/release.yaml
scripts/release_index_ci_check.py

* Simplify the release index checks.  It no longer attempts to mark actions as successful, because those actions are now only running when pertinent.
* Add an additional `paths-ignore` entry in the relevant places, based on the release index checks paths.

Reform Github checks

---

.github/workflows/main.yaml
.github/workflows/push/action.yaml
.github/workflows/release-controller.yaml

We use Bazel's `pushed blob` status update to detect when a container was actually pushed to the container registry.

Push images and update deployments only when containers are actually pushed.

---

.github/workflows/main.yaml
.github/workflows/push/action.yaml
.github/workflows/release-controller.yaml

The secret is not available in the composite action.
Fixes this:

Add push-token input for OCI image pushing

---

rs/decentralization/src/lib.rs

- Adjust the `Display` of `SubnetChangeResponse` to show closer to the top the impact of change on business rules checks.
Community members asked for this in the [forum](https://forum.dfinity.org/t/subnet-management-6pbhf-application/33765/60)

refactor(decentralization): move impact on business rules toward top in SubnetChangeResponse display

---

rs/cli/BUILD.bazel

Each time a push happens to a PR, `dre` gets rebuilt, because the version changes.  CLI unit tests depend on this target.  As a result, the tests are run all over again, wastefully, for no good reason at all.
This PR fixes that.
This change does *not* make the build of the `dre` target cacheable!  This change only makes the tests depend on the cacheable version of the target.
Before:
After:
Rant:
We should strongly consider not adding any version junk into any of our binaries **unless those binaries are going to go through an actual release pipeline** (e.g. the actual `dre` binary built for user download).  Stuff shipped in containers _does not need a version number!_  The container already has that information in the tag.

Make DRE CLI tests cacheable.

---

.github/workflows/push/action.yaml

This update redirects the standard error stream (stderr) to the standard output stream (stdout) for the bazel command within the GitHub action workflow. This change ensures that all command outputs are captured in the tee file, to capture the actual pushed blob text needed to trigger the caller action to create or update the PR.

Fix: Redirect stderr to stdout for bazel command in GitHub action

---

release-controller/README.md

Updated the README.md file to reflect that the release controller now automates parts of the process for proposing new releases for both IC HostOS and GuestOS.
Added instructions on how to view production logs in real time using Grafana.
Corrected the usage documentation regarding the `--skip-preloading-state` option.
Updated the instructions for running unit tests and added information about building all tests with MyPy types.

Release controller documentation enhancements.

---

release-controller/git_repo.py
release-controller/reconciler.py

- Changed the log level of `GitRepo.fetch` from `INFO` to `DEBUG` to provide more detailed information about repository updates.
- Added a conditional check in `Reconciler` to only log the number of releases processed if there are any versions.

Quiet down the release controller's components

---

.github/workflows/dashboard.yaml
.github/workflows/update-dependencies.yaml

- Update GitHub Actions workflows to run on Ubuntu 22.04.
- Update commands to install Rust tools with locked dependencies.
- Update Rust toolchain to stable version.

build: upgrade CI to Ubuntu 22.04

---

.github/workflows/dashboard.yaml
.github/workflows/main.yaml
.github/workflows/release-controller.yaml
.github/workflows/trusted-neurons-alerts.yaml

For some reason now Bazel is not actually printing when it's pushing containers out to the container registry.  This broke the creation of PRs to update containers in k8s.
Thus, we now unconditionally create or update the rollout PRs when merging to `main`, and additionally when the workflow is manually dispatched.

Fix creation of rollout PRs for containers in k8s

---

.github/workflows/manage-runner-pre/action.yaml

V2 started failing since yesterday.
bazelbuild was archived by the owner on Mar 11, 2024. It is now read-only. 
We should update to https://github.com/bazel-contrib/setup-bazel

Update setup-bazelisk to v3 to fix our CI

---

release-controller/reconciler.py

This change enables INFO level logging for the `pydiscourse.client` module.  At DEBUG level, `pydiscourse.client` produces enormously long lines with all the content of the forum posts, which then get chopped up by our logging infrastructure and appear as random noise on our dashboards.
This will require a quick rollout of the reconciler.

Quiet down logging for pydiscourse.client

---

rs/dre-canisters/node-provider-rewards/canister/src/lib.rs
rs/dre-canisters/node-provider-rewards/canister/src/telemetry.rs

Moved PrometheusMetrics from lib.rs to its own telemetry module for better organization and separation of concerns.

Refactor PrometheusMetrics to separate telemetry module.

---

release-controller/commit_annotator.py
release-controller/reconciler.py

This makes it so that the watchdog only crashes and restarts the process when the process is truly stuck.

Call the watchdog when there's a handled exception.

---

rs/dre-canisters/node-provider-rewards/canister/src/lib.rs
rs/dre-canisters/node-provider-rewards/canister/src/telemetry.rs

This PR introduces instruction counters (as Prometheus gauges) that allow telemetry observers to see:
* the count of instructions that the last sync incurred,
* specific counts of instructions for subnet list, update metrics, registry sync, specifically during the last sync.

Instruction counter metrics.

---

release-controller/reconciler.py

With this, we will get telemetry of successful release notes preparation even when the notes do not need to be prepared, enhancing the consistency of the telemetry we get.
This also allows us to capture and record telemetry for any exceptions within the check portion of the phase, which was previously not wrapped in the phase decorator.

fix(reconciler): Wrap the entire phase of release notes preparation into the phase decorator.

---

Cargo.Bazel.lock
Cargo.lock
MODULE.bazel
images/BUILD.bazel
images/ubuntu_24_04_packages.lock.json
images/ubuntu_24_04_packages.yaml
release-controller/BUILD.bazel
release-controller/README.md
release-controller/commit_annotation.py
release-controller/commit_annotation_recreator.py
release-controller/commit_annotator.py
release-controller/release_notes_composer.py
rs/cli/BUILD.bazel
rs/cli/Cargo.toml
rs/cli/src/auth.rs
rs/cli/src/lib.rs
rs/cli/src/pin/ask.rs
rs/cli/src/pin/keyring.rs
rs/cli/src/pin/mod.rs
tools/python/py_oci_image.bzl

The commit annotator and the reconciler switch in this release to be shipped in a minimal Ubuntu 24.04 container, with the requisite dependencies added for them to work properly.  Image size has gone down accordingly (first image is the old one, second is the locally built one):
```
REPOSITORY                              TAG                                       IMAGE ID      CREATED       SIZE
ghcr.io/dfinity/dre/release-controller  ab1d8ef1aec27b53a94fcd9bb720be12e8680f60  256020b26a92  5 months ago  1.71 GB
<none>                                  <none>                                    56e16585497e  55 years ago  1 GB
```
To debug the execution of these containers, it is now possible to load them via `podman` and then run them locally.  They operate correctly as far as I could tell. …

Switch release controller components to Ubuntu 24.04 / stop papering over annotation failures

---

images/BUILD.bazel

This commit adds support for creating a user home directory in the OCI image.
It includes a `home` rule with two entries for `/root` and `/home/user`, providing appropriate UID, GID, and shell configurations for each user.
This fixes the release controller crashing because it wants to write to `/.cache`.

feat: add user and root home directories for containers

---

images/ubuntu_24_04_packages.lock.json
images/ubuntu_24_04_packages.yaml

Without this package, HostOS commit annotation fails.

Add libffi-dev package for building the IC.

---

Cargo.lock
rs/dre-canisters/node-provider-rewards/canister/api/src/endpoints.rs
rs/dre-canisters/node-provider-rewards/canister/src/registry.rs
rs/dre-canisters/node-provider-rewards/rewards-calculation/src/rewards_calculator.rs
rs/dre-canisters/node-provider-rewards/rewards-calculation/src/rewards_calculator/builder.rs
rs/dre-canisters/node-provider-rewards/rewards-calculation/src/rewards_calculator/tests.rs
rs/dre-canisters/node-provider-rewards/rewards-calculation/src/rewards_calculator_results.rs
rs/dre-canisters/node-provider-rewards/rewards-calculation/src/types.rs

This PR add to `ProviderRewardableNodes` the rewardable_nodes_count present in the registry.
This is used to correctly compute the base rewards per `region` `node_type` in `RewardsCalculator`

Fix correct base rewards computation

---

rs/ic-observability/multiservice-discovery-shared/src/builders/general_exec.rs
rs/log-fetcher/src/main.rs

Since we have some issues with ratelimiting on some nodes this PR tries to use open connections until they break, and only if they break, it recreates a new one.

refactor: using open connections to fetch logs

---

images/BUILD.bazel
images/ubuntu_24_04_packages.lock.json
release-controller/dryrun.py
release-controller/google_docs.py
release-controller/reconciler.py

When we moved to Ubuntu 24.04 for the container package of the reconciler, something changed in the way that the container was built, such that Bazel-wrapped Python binaries (such as the reconciler) silently failed to load the system certificate store, leading to Python `urllib.request.urlopen` failing to load HTTPS resources.  Since `urllib` is how the Slack SDK posts announcements about GuestOS and HostOS, that begun failing (fortunately not in a way that prevented making progress with the release process).
This failure does not affect usage of the `requests` because `requests` uses the `certifi` certificate store by default (although if we were using a private certificate authority for some of our requested resources, this would not work and it would require the use of the environment …

fix(reconciler): correct issue with reconciler and Slack messages.

---

.github/workflows/required-checks.yaml

Updated concurrency group to include push events in addition to pull requests and branch creation. This ensures that required checks workflows do not get cancelled when a merge is done into `main`. This will also clear up the ocean of red crosses in the commit history for `main`.
EDIT: we won't actually know if this did work until we merge to `main`.  Guh.

fix(ci): concurrency group for required checks

---

Cargo.Bazel.lock
Cargo.lock
rs/dre-canisters/node-provider-rewards/canister/Cargo.toml
rs/dre-canisters/node-provider-rewards/canister/api/src/endpoints.rs
rs/dre-canisters/node-provider-rewards/canister/src/lib.rs
rs/dre-canisters/node-provider-rewards/canister/src/telemetry.rs

Introduce functionality to exercise, hourly, the query calls `get_node_providers_rewards` and `get_node_provider_rewards_calculation` based on current time, and measure execution cost (instruction count) for them.
Adds `chrono` dependency for date/time handling.  The method to determine the next 1 AM has been changed.
Addresses https://dfinity.atlassian.net/browse/DRE-390 .

feat(node-provider-rewards): Add query call measurement and telemetry

---

Cargo.Bazel.lock
Cargo.lock
Cargo.toml
rs/dre-canisters/node-provider-rewards/canister/Cargo.toml
rs/dre-canisters/node-provider-rewards/canister/src/lib.rs
rs/dre-canisters/node-provider-rewards/canister/src/metrics.rs
rs/dre-canisters/node-provider-rewards/canister/src/metrics/tests.rs
rs/dre-canisters/node-provider-rewards/canister/src/registry_canister.rs
rs/dre-canisters/node-provider-rewards/canister/src/storage.rs

Changes:
- Bump `ic-cdk `dep to 0.18 (where bounded calls are supported)
- Adapt metrics fetching to use bounded calls
- Adapt tests 
- Introducing `RegistryClient` to query registry using bounded calls
TODO:
- Remove `RegistryClient` once `RegistryClient` in IC repo depends on `ic-cdk 0.18`

feat(node-provider-rewards): Perform inter-canister calls using non-blocking calls

---

rs/dre-canisters/node-provider-rewards/canister/src/lib.rs
rs/dre-canisters/node-provider-rewards/canister/src/telemetry.rs

The metrics labeled `method=node_provider_rewards_calculation` all gain a label `operator` to distinguish results from operator to operator.

Dispatch one hour timer interval per node operator to measure them separately.

---

rs/dre-canisters/node-provider-rewards/README.md

This commit adds a new README.md file for the node-provider-rewards canister, providing guidance on suggested Prometheus alert formulas.
The document includes details on how to add job labels and outlines several alert formulas to monitor different aspects of the canister's operation, such as sync failures, stalls, query call failures, intensive queries, and large response sizes.

feat: Added README.md for node-provider-rewards canister with Prometheus alert formulas.

---

release-controller/BUILD.bazel
release-controller/public_dashboard.py
release-controller/reconciler.py
release-controller/reconciler_state.py
release-controller/release_index.py
release-controller/release_index_loader.py
release-controller/tests/test_reconciler.py
release-index-schema.json
release-index.yaml
rs/cli/src/commands/proposals/filter.rs

* Process for proposal creation only latest two release.
* Handle potential errors fetching the image packages better.
* Allow override of the base version used for the changelog in the index.
* Consult dashboard API (optionally) to obtain latest proposals, and thus prevent resubmission of versions already submitted in the past.  The option to disable this behavior has been removed.

Release controller fixes

---

release-controller/README.md
release-index.yaml

Because we didn't really have any documentation explaining how it worked before.

Update README.md with detailed release index reference info

---

README.md
facts-db/non_default_subnets.csv
facts-db/non_public_subnets.csv
rs/cli/src/commands/main_command.rs
rs/cli/src/commands/mod.rs
rs/cli/src/commands/update_default_subnets.rs
rs/ic-canisters/src/cycles_minting.rs

- Renamed CLI command and alias:
- `update-authorized-subnets` → `update-default-subnets` (with visible alias for backward compatibility)
- Updated code identifiers to match new name:
- Module, struct, and function names (`UpdateAuthorizedSubnets` → `UpdateDefaultSubnets`, `get_authorized_subnets` → `get_default_subnets`)
- Cleaned up facts database:
- Removed `non_public_subnets.csv`
- Dropped obsolete `shefu` entry from `non_default_subnets.csv` as per https://github.com/dfinity/ic/pull/592
- Updated documentation in `README.md` to reflect the new command name

refactor(cli): rename update-authorized-subnets to update-default-subnets

---

release-controller/reconciler.py
rs/cli/src/main.rs

* Add package checksum and unelected revisions logging, to verify during the next release that revisions are being unelected.
* Remove constant "Running version 0.0.0" when running `dre-embedded` in the reconciler.  Pointless, spams the log.

Improve logging in the reconciler

---

rs/cli/src/commands/registry.rs

Resolved panic by logging warning and returning an empty map when the node operator has nodes in the registry and rewardable nodes, but somehow no node reward types.
- Replaced `panic!` with `warn!` to log the issue instead of terminating execution.
- Provided detailed information in the log, including the principal, total nodes allowed, and reward types count.
Addresses (but does not necessarily fix) https://dfinity.atlassian.net/browse/DRE-466 .

Fix(dre): Handle unexpected zero node reward types count

---

cordoned_features.yaml

Added new node provider 'spp3m-vawt7-3gyh6-pjz5d-6zidf-up3qb-yte62-otexv-vfpqg-n6awf-lqe' for Rivonia's node sale per DFINITY agreement. For more information, see https://dfinity.slack.com/archives/C02BEQD3410/p1749652046739739.

Cordon off Rivonia

---

rs/log-fetcher/src/journald_parser.rs
rs/log-fetcher/src/main.rs

Given the journald protocol it is possible to fetch partial messages when fetching chunks. If the field is binary encoded it will contain the `\n\n` that we used for determining if the message is complete or not. Given that regular nodes rarely have binary encoded fields we didn't notice it. 
When developing configuration for new http-gateway scraping the issue came up as they have a couple of fields within the same log entry that are binary encoded. This will fix that issue and allow for proper batching

fix: `log-fetcher` proper buffering logic

---

release-controller/util.py

This change updates the `DefaultSubcommandArgParser` class to support additional arguments passed during its initialization. This invocation function signature changed in Python 3.12.7 and we did not update when the containers were updated to latest stable Python, causing this to fail in prod.
With this fix, the parser works.

Fix use of DefaultSubcommandArgParser.

---

release-controller/reconciler.py

Moved launch measurements fetching logic into its own block, ensuring it runs for all GuestOS versions. This also fixes an unbound variable issue.

Reorganize launch measurements handling for GuestOS and HOSTOS.

---

rs/cli/src/ctx/mod.rs
rs/cli/src/exe/args.rs
rs/cli/src/operations/hostos_rollout.rs
rs/ic-management-backend/src/health.rs

Problem (Why?)
- Need a way to force health states for nodes or data centers for testing and troubleshooting.
Solution (What?)
- Add a CLI option to specify health overrides and propagate them to the backend via an environment variable (DRE_OVERRIDE_HEALTH).
- Backend parses the overrides and applies them to health responses from local cache, Public Dashboard, and Prometheus clients.
Example usages: `--override-health sg2:healthy` or `--override-health mn2:healthy de1:dead`
Accepted values (case-insensitive): healthy, degraded, dead, unknown
Example proposal submitted with this: https://dashboard.internetcomputer.org/proposal/138159
(ignoring the sg2 DC being down/unhealthy)

feat(health): allow overriding node health via CLI and env

---

cordoned_features.yaml

- Pruned obsolete node_provider entries from cordoned_features.yaml.

chore(cordoned-features): prune deprecated node_provider entries

---

.github/workflows/dre-release.yaml
docker/runner.Dockerfile
rs/cli/README.md
rs/cli/src/store.rs

- macOS release builds failed to produce multi-arch artifacts and publish them correctly.
- Extend CI to build and publish macOS x86_64 and aarch64 artifacts and adjust release job to depend on them.
- Make ic-admin download URL arch-aware on macOS by selecting x86_64-darwin or aarch64-darwin.
- Update tooling in the image: Zig 0.16.0, macOS SDK 16.2, and Rust toolchain 1.86.0; rename artifacts in release and prune old libs.
- ic-admin arch mapping logic is isolated to the Darwin branch to avoid Linux changes.
- Release workflow now downloads and renames macOS artifacts to standard dre-x86_64-apple-darwin and dre-aarch64-apple-darwin names.
- Documentation cleanup: removed libssl troubleshooting notes from RS CLI README.

fix(darwin-release): fix macOS release builds for x86_64 and aarch64

---

docs/firewall-proposals.md
docs/index.md

- Provide a concise, end-to-end guide for submitting firewall proposals via DRE CLI.
- Added docs/firewall-proposals.md detailing prerequisites, scopes, interactive flow, and examples.
- Updated docs/index.md to link the new page under the docs section.
- None; docs-only change.
- Per-scope workflows mirror the global example and emphasize single-change per run.
- Keeps rule shapes consistent with existing rules and highlights dry-run mode.
updated docs accordingly

docs(firewall-proposals): add submitting firewall change proposals guide
