.bazelrc
.github/workflows/bazel.yaml
bin/optimize-bazel-cache.sh

Reduces the bazel cache size from close to 10GB compressed to 3.1GB.

perf(ci): Reduce the bazel cache size

---

.github/workflows/bazel.yaml

Fix the reference to the GitLab API token in the CI/CD pipeline.

Fix reference to GitLab API token

---

docs/k8s/tips-and-tricks.md

docs: Add some tips and tricks for our k8s ops

---

.github/workflows/update-dependencies.yaml

Fixing leftover name of refactoring from here:
https://github.com/dfinity/dre/actions/runs/7690062449/job/20953364937

ci: fixing leftover name of step

---

rs/ic-observability/multiservice-discovery/src/definition.rs
rs/ic-observability/multiservice-discovery/src/main.rs
rs/ic-observability/multiservice-discovery/src/server_handlers/add_definition_handler.rs
rs/ic-observability/multiservice-discovery/src/server_handlers/export_prometheus_config_handler.rs
rs/ic-observability/multiservice-discovery/src/server_handlers/export_targets_handler.rs
rs/ic-observability/multiservice-discovery/src/server_handlers/mod.rs

Useful for @pietrodimarco's tests.

Add command-line option to print targets to stdout.

---

.github/workflows/msd-diff.yaml
rs/ic-observability/multiservice-discovery-shared/src/builders/prometheus_config_structure.rs

* Added workflow to comment with a `git diff` main vs pr if something changes in the targets.

Add MSD visual diff

---

.github/workflows/main.yaml
.github/workflows/manage-runner-post/action.yaml
.github/workflows/manage-runner-pre/action.yaml

The force overwriting implementation comes from https://github.com/actions/cache/blob/a2ed59d39b352305bdd2f628719a53b2cc4f9613/tips-and-workarounds.md?plain=1#L38

feat(ci): Bump up the actions/cache to v4, and force overwriting the cache

---

Cargo.Bazel.lock
Cargo.lock
Cargo.toml
rs/ic-management-backend/src/health.rs
rs/ic-management-backend/src/release.rs

- no functional change
- I've tested that the new version works as expected with a local run of `yarn dev`

chore(dashboard): Update the version of prometheus-http-client

---

.github/workflows/main.yaml

Slack thread: https://dfinity.slack.com/archives/CL7Q2RXUM/p1708083952483639

Updating the k8s repo token, to the one managed by IDX.

---

.gitignore
.vscode/settings.json
release-index-shema.json
release-index.yaml

In this PR I propose a schema for versioning our releases. The goal is make the process more transparent and to allow for future automation of the release story. With this addition (plus further automation) we would ideally have to create a MR with the information for the upcoming release week which would be reviewed by us. Once we approve, we could automatically create further rollout steps. This week we have a feat build and these were required subnets:
```
fuqsr-in2lc-zbcjj-ydmcw-pzq7h-4xm2z-pto4i-dcyee-5z4rz-x63ji-nae
4zbus-z2bmt-ilreg-xakz4-6tyre-hsqj4-slb4g-zjwqo-snjcc-iqphi-3qe
bkfrj-6k62g-dycql-7h53p-atvkj-zg4to-gaogh-netha-ptybj-ntsgw-rqe
csyj4-zmann-ys6ge-3kzi6-onexi-obayx-2fvak-zersm-euci4-6pslt-lae
ejbmu-grnam-gk6ol-6irwa-htwoj-7ihfl-goimw-hlnvh-abms4-47v2e-zqe …
```

feat(release): Proposing release index shema

---

.github/workflows/manage-runner-post/action.yaml

Likely cause of failure here https://github.com/dfinity/dre/actions/runs/8042519935/job/21963284953

fix(ci): Fix case of github_token variable

---

release-index.yaml

Background: https://dfinity.slack.com/archives/C01DB8MQ5M1/p1712044633976519

Release: add an ECDSA hotfix

---

rs/cli/src/clients.rs
rs/ic-observability/multiservice-discovery/README.md
rs/ic-observability/multiservice-discovery/src/definition.rs
rs/ic-observability/multiservice-discovery/src/main.rs
rs/ic-observability/multiservice-discovery/src/server_handlers/export_prometheus_config_handler.rs
rs/ic-observability/multiservice-discovery/src/server_handlers/export_targets_handler.rs

Filtering by datacenter ID, node provider, subnet, and IC name are implemented.

Implement filtering for the discovery service.

---

rs/ic-observability/multiservice-discovery/src/server_handlers/export_prometheus_config_handler.rs

We were returning a plain string alone which causes Axum to respond with content type `text/plain`.  This is very bad and causes modern Prometheus to ignore the response completely.  Set the right header instead, to make Prometheus work.
Tested: working locally with Prometheus.
Diff printed below is no longer valid.  Second commit of this PR which caused the diff was split to https://github.com/dfinity/dre/pull/316

Correct content type.

---

.github/workflows/build/action.yaml

Hide output of dry-run execution when successful.

---

Cargo.Bazel.lock
Cargo.lock
rs/cli/Cargo.toml
rs/cli/src/main.rs

Notes:
* If the tool is up to date, or the user refuses to update the tool will proceed
* If the tool fails to update for some reason it will exit
* If the tool is updated it will early exit so the user can rerun with the new version
Example of usage of the tool:

feat(dre): implemented automatic updates for dre tool

---

Cargo.Bazel.lock
Cargo.lock
Cargo.toml
WORKSPACE.bazel
rs/cli/src/registry_dump.rs
rs/ic-management-backend/src/proposal.rs
rs/ic-management-backend/src/registry.rs
rs/ic-management-types/src/lib.rs
rs/ic-observability/service-discovery/src/mainnet_registry.rs
rs/ic-observability/service-discovery/src/registry_sync.rs
rs/rollout-controller/src/calculation/stage_checks.rs

Alongside this there are some minor changes related to aligning with a newer version of IC repo. Those were needed since there were renamings in the upstream proposal paylod struct names

feat(dre): adding api boundary nodes to registry dump command

---

.github/workflows/main.yaml
.github/workflows/release.yaml
factsdb/mainnet-labels.yaml
factsdb/staging-labels.yaml

Adding structure for node labels for mainnet and staging.

feat: adding v1 structure for node labels in dre repo

---

rs/cli/src/operations/hostos_rollout.rs
rs/ic-management-backend/src/endpoints/mod.rs
rs/ic-management-backend/src/endpoints/nodes_ops.rs
rs/ic-management-backend/src/endpoints/subnet.rs
rs/ic-management-backend/src/health.rs
rs/ic-management-backend/src/registry.rs
rs/ic-management-types/src/lib.rs
rs/np-notifications/src/health_check.rs

Improvement towards using `dre` tool without vpn

feat: adding using of public dashboard for mainnet for health statuses

---

release-controller/release_notes.py

Changes made by interface-owners should be visible in the release notes.
slack thread: https://dfinity.slack.com/archives/C01DB8MQ5M1/p1715332190681769

fix(release-notes): Ensure "interface-owners" changes are included

---

Cargo.Bazel.lock
Cargo.lock
bin/bazel-cache-s3-start.sh
rs/cli/Cargo.toml
rs/cli/src/detect_neuron.rs
rs/cli/src/general.rs
rs/cli/src/ic_admin.rs
rs/cli/src/main.rs
rs/cli/src/parsed_cli.rs
rs/cli/src/runner.rs
rs/rollout-controller/src/actions/mod.rs
rs/rollout-controller/src/main.rs

This allows running dre tool without an HSM/private key to dry-run the proposal submission (without submitting).

feat(cli): DRE-120 Lazily check for HSM/private key auth

---

release-controller/governance.py
release-controller/prometheus.py
release-controller/reconciler.py
release-controller/test_reconciler.py

fix(release-controller): [DRE-166] Add timeouts to the URL requests

---

.bazelignore
rs/cli/src/defaults.rs

These changes should have virtually no effect on regular use

chore: Update bazelignore and update default IC_ADMIN version

---

.github/workflows/main.yaml
.github/workflows/manage-runner-pre/action.yaml
.github/workflows/msd-diff.yaml
.github/workflows/update-dependencies.yaml
.pre-commit-config.yaml
release-index-schema.json

This PR updates the poetry and cargo dependencies and recreates the bazel cache.

chore(ci): Update dependencies and recreate bazel cache

---

release-controller/publish_notes.py
release-controller/slack_announce.py

selection of teams based on a slack poll: https://dfinity.slack.com/archives/CH4CADCJX/p1715951305394969

chore(release-controller): Do not ping all teams to review release notes

---

rs/cli/src/cli.rs
rs/cli/src/main.rs
rs/ic-canisters/src/governance.rs

This allows fetching full proposal information, including the payload.

feat(dre): Add a proposals subcommand to get a single proposal by id

---

rs/cli/src/cli.rs
rs/cli/src/operations/hostos_rollout.rs
rs/cli/src/runner.rs

The HostOS rollout did not have the local registry correctly populated so it couldn't calculate the rollout strategy.

fix(dre): Fix for the HostOS rollout in groups

---

Cargo.Bazel.lock
Cargo.lock
Cargo.toml
rs/ic-canisters/Cargo.toml
rs/ic-canisters/src/governance.rs
rs/ic-canisters/src/lib.rs
rs/ic-management-backend/src/proposal.rs
rs/ic-observability/obs-canister-clients/Cargo.toml
rs/ic-observability/obs-canister-clients/src/node_status_canister_client.rs
rs/slack-notifications/src/main.rs
rs/slack-notifications/src/slack.rs

We observed that the NNS proposal notification bot got stuck while checking for failed proposals.

fix: Add a time for all agent-rs (canister) clients

---

release-controller/release_notes.py
scripts/release-notes.py

This was requested internally and [on the forum](https://forum.dfinity.org/t/proposal-to-elect-new-release-rc-2024-06-12-23-01/31933/8?u=sat).

feat(release-notes): Use merge commits if available, and fall back to the non-merge

---

release-index.yaml

https://dfinity.slack.com/archives/C020G13AS4F/p1719223911614749

Update release-index.yaml to cut fix for lhg73

---

.github/workflows/release.yaml
.pre-commit-config.yaml
.vscode/settings.json
release-controller/ci_check.py
release-index.yaml

Example of successful CI with warnings: https://github.com/dfinity/dre/actions/runs/9665911604/job/26664172436?pr=534
Example of CI with errors: https://github.com/dfinity/dre/actions/runs/9665980671/job/26664410826?pr=534

feat: enabling ci checks for release-index.yaml

---

rs/slack-notifications/conf/neurons-slack-mapping.yaml

Add neuron to Slack mapping for Mathias.

chore: Add mapping for Mathias' neuron

---

release-index.yaml

Qualification runs are not done but they are expected to finish.  Will be merged once it's done.

Release 2024-06-26_21-01

---

rs/ic-canisters/src/management.rs

chore(dre): Cleanup old and now unused trustworthy metrics structs

---

rs/cli/src/cli.rs
rs/cli/src/main.rs
rs/cli/src/operations/hostos_rollout.rs
rs/cli/src/registry_shared.rs
rs/cli/src/runner.rs
rs/ic-management-backend/src/registry.rs

- Check the health of the nodes that were already upgraded to the new version
- Added the ability to filter in or filter out nodes for the rollout by some feature(s)
- Improved logging

feat(hostos):  HostOS rollout improvements

---

Cargo.Bazel.lock
Cargo.lock
rs/cli/Cargo.toml
rs/cli/src/auth.rs

fix(dre): adding back autodetection of hsm

---

rs/cli/src/commands/vote.rs
rs/cli/src/main.rs

This makes logging across all execution more consistent and traceable.

feat(dre): Add time to all dre tool logs, and remove it from voting events only

---

release-controller/release_index.py
release-index-schema.json

Includes a run of `/bin/poetry.sh`

fix: schema root namings

---

rs/ic-management-backend/src/health.rs

This pull request refactors the `health.rs` file to improve error handling and readability. The changes include updating the code to handle errors when fetching data from the public dashboard and parsing JSON responses.

chore: Refactor health.rs for improved error handling and readability

---

Cargo.Bazel.lock
Cargo.lock
Cargo.toml
WORKSPACE.bazel
docker/Dockerfile
ic-revisions.json
poetry.lock
pylib/ic_admin.py
requirements.txt
rs/cli/src/ic_admin.rs
rs/ic-observability/multiservice-discovery/Cargo.toml

This PR updates poetry (Python) and cargo (Rust) dependencies and IC repository dependencies

chore: Update dependencies

---

rs/decentralization/src/nakamoto/mod.rs
rs/decentralization/src/network.rs

The latest target topology is described in https://dashboard.internetcomputer.org/proposal/132136

feat(decentralization): Add distance from the target topology as business rules

---

release-controller/reconciler.py

feat(release-controller): auto-retry proposal placement

---

docker/runner.Dockerfile

Adds missing parts to the docker image for running `softhsm2` for tests

fix: adding opensc and chown on dirs

---

release-controller/release_notes.py
release-controller/test_release_notes.py

fix(release-controller): Don't exclude canister_state files

---

rs/ic-observability/multiservice-discovery/src/main.rs

The change is implemented with regards to the following considerations:
1. Not breaking the api. Old usages of the tool will still work in the same fashion.
2. Allowing to run with just one network. This is how it used to work previously.

feat(msd): adding option to start with just staging 

---

.github/workflows/qualify.yaml

It's not working as is, anyway.

chore(ci): Again disable qualification in the CI

---

release-controller/release_index_loader.py
release-controller/test_release_index_loader.py

No functional change, just making pre-commit happy

chore(release): Format the code in release-controller/

---

Cargo.Bazel.lock
Cargo.lock
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics-types/Cargo.toml
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics-types/src/types.rs
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics/src/lib.rs
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics/src/rewards_manager.rs
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics/src/stable_memory.rs

Updates daily `NodeRewardTable` and store it in stable mem

Update node reward table to compute XDR with penalties

---

rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics-frontend/src/components/NodePerformanceChart.tsx
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics-frontend/src/components/NodeProviderChart.tsx
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics-frontend/src/components/NodeProviderPage.tsx
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics-frontend/src/components/NodeProviderRewards.tsx
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics-frontend/src/components/NodeRewardsChart.tsx
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics-frontend/src/components/RewardTable.tsx
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics-frontend/src/utils/utils.tsx
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics-types/src/types.rs
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics/src/computation_logger.rs
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics/src/lib.rs
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics/src/rewards_manager.rs
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics/src/stable_memory.rs
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics/trustworthy-node-metrics.did

- Added node providers rewards algorithm with Rewards Reduction
- Updated dashboard to display latest node provider rewards
- Added base rewards value per node in dashboard

Node Providers rewards XDR

---

docker/runner.Dockerfile

Updating runner version and zig in that version

chore: new runner 

---

rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics-frontend/src/components/NodePerformanceChart.tsx
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics-frontend/src/components/NodeProviderChart.tsx
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics-frontend/src/components/NodeProviderPage.tsx
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics-frontend/src/components/NodeProviderRewards.tsx
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics-frontend/src/components/NodeRewardsChart.tsx
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics-frontend/src/components/RewardTable.tsx
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics-frontend/src/utils/utils.tsx
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics-types/src/types.rs
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics/src/computation_logger.rs
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics/src/rewards_manager.rs
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics/src/stable_memory.rs
rs/dre-canisters/trustworthy-node-metrics/src/trustworthy-node-metrics/trustworthy-node-metrics.did

- modified `compute_np_rewards` to make it testable
- added tests for the function
- Adjusted frontend for the changes

Add tests NP Rewards function

---

release-controller/README.md

Document recreating notes

---

rs/slack-notifications/src/slack.rs

Eliminate the internal dashboard link from the proposal motivation for subnet management changes.

Remove internal dashboard link for subnet membership changes in proposal motivation

---

rs/decentralization/src/lib.rs

Eliminate the decentralization impact calculation from the SubnetChangeResponse struct and from the NNS proposals summary for the subnet membership change proposals.

Refactor SubnetChangeResponse by removing decentralization impact calculation

---

rs/cli/src/commands/network.rs
rs/cli/src/runner.rs
rs/decentralization/src/network.rs

This should give us a chance to further improve network topology and decentralization.

feat(dre,network): add "network --ensure-operator-nodes-unassigned"

---

rs/cli/src/runner.rs

Not completely sure if this check is required, but better to be on the safe side.

fix(dre): Explicitly check if nodes are in open proposals for network --ensure-*

---

release-controller/README.md
release-controller/commit_annotator.py
release-controller/git_repo.py
release-controller/reconciler.py

Enhance logging for commit annotation and branch processing. Introduce a watchdog to monitor the health of the release controller process.

feat(release): Refactor annotator logging and add watchdog functionality

---

Cargo.Bazel.lock
Cargo.lock
rs/decentralization/src/network.rs
rs/decentralization/src/network_tests.rs

If possible (and without reducing decentralization), prioritize nodes from operators that have more unassigned nodes.

feat: update node selection logic to prioritize unassigned nodes of large operators

---

.github/workflows/main.yaml

It does not appear that you actually needed a custom token here, so I am removing it.

chore(IDX): remove custom token

---

Cargo.lock
docs/chat/icp-support.md
mkdocs.yml

This PR reorders navigation on github pages and includes a new "Chatbot" page and adds it to the top of our docs. It will render an IFrame to the support bot that we use for user's to submit issues.

chore: reordering nav for github pages

---

release-index.yaml

Slack thread: https://dfinity.slack.com/archives/C01DB8MQ5M1/p1734080394696469?thread_ts=1733240501.097579&cid=C01DB8MQ5M1

chore(release): add a sandboxes7k version

---

rs/cli/src/commands/update_authorized_subnets.rs

Previous logic was also proposing to close some of the open verified subnets. This change will open 1 *more* verified subnet.
Also update default value for open_verified_subnets, to open up 1 more verified subnets if an explicit value was not provided.
Example proposal submitted with this code:
https://dashboard.internetcomputer.org/proposal/134498

fix: improve logic for opening up verified subnets

---

k8s/boundary-node-service-discovery/boundary-node-service-discovery.py

It turns out this script is still needed so here is a fix for its migration to github from gitlab.

fix: boundary nodes update script migration to github

---

docker/runner.Dockerfile

Should fix this failure: https://github.com/dfinity/dre/actions/runs/12742662828/job/35511153092?pr=1188

fix(docker): remove cargo-deny installation

---

rs/cli/src/discourse_client.rs

Discourse treats subcategories as categories that have a `parent` but returns a weird structure that is recursive. After this PR the proposals that are automatically created by the dre tool will have a category looking like the following:

chore: using `NNS proposal discussion` category for creating new posts

---

docs/be-dr-dre.md
mkdocs.yml

Adds some context to what we should do on weekly rotations. This will for sure change over time, but it should be a starting point

docs: specifying what is required of dr dre

---

release-controller/reconciler.py
release-controller/slack_announce.py

Fix Slack announcement in release controller.

---

release-controller/reconciler.py

Now I have come to appreciate the specific type nature of Rust durations.

Never attempt to sleep a negative number of seconds.

---

docs/be-dr-dre.md

Added the following update to Dr. DRE's release process document:
- Updated the list of tasks that need to be completed during each week.
- There is more than one weekly dependency upgrade job.
- Mention both types of dependency upgrade jobs and where to find them.
- Modified the description for submitting proposals conventionally submitted once a week.
- Some information was incorrectly under the Weekly dependency upgrade jobs heading.

Update Dr. DRE documentation.

---

release-controller/reconciler.py

This was not being properly addressed.

Correct reconciler log message.

---

pyproject.toml

- Added guidance on using `rye` for adding dependencies and dev-dependencies to ensure correct section placement and lock file updates.

docs: add guidance on managing dependencies in pyproject.toml

---

rs/cli/src/subnet_manager.rs

- Consolidated logging operations for replaced nodes.
- Streamlined the construction of the 'motivations' vector.
- Utilized iterator chaining to improve code readability and maintainability.

refactor: reduce redundant motivation messages for node swap proposals

---

rs/cli/src/commands/network.rs

- Extend cli argument validation logic in `validate` function of `Network` to include a new `--optimize-decentralization` option.

feat(cli): add `--optimize-decentralization` validation

---

rs/decentralization/src/network/types.rs

To satisfy `cargo clippy --tests`

feat: add Serialize to CordonedFeature

---

.github/workflows/check-modified-files-as-step/action.yaml

This should use the github event before and after SHA hashes:

Fix file modification detection on the case of push to branch.

---

docs/be-dr-dre.md

- **Release Process**: Outline updated steps and timeline for GuestOS & HostOS release preparation and review.
- Various other minor corrections and clarifications

docs: clarify DRE rotation and release process

---

rs/decentralization/src/network/healing.rs

- **Penalty Handling**: 
- Introduces variable `penalty_original` to capture the initial penalty for comparison.
- Conditions added to determine if penalty improvements occurred, guiding decision logic.
- **Optimization Logic**: 
- Filters solutions by minimal penalty and selects best by maximum Nakamoto Coefficient.
- Identification of whether a solution penalty is improving to refine node replacement motivations.
- **Logging and Motivation Update**: 
- Adds detailed logging and update node replacement motivations based on penalty improvements.

feat: optimize network healing penalty handling

---

.github/workflows/release-controller.yaml

Please only merge after https://github.com/dfinity-ops/k8s/pull/1164 is in.

Refine release controller deployment update

---

release-controller/dre_cli.py
release-controller/dryrun.py
release-controller/reconciler.py

This commit updates the verb used in the propose command argument, from 'replica' to 'guestos'.
This addresses a crash in the proposal cycle of the reconciler.

Update to latest IC admin propose verbiage.

---

rs/log-fetcher/src/main.rs

https://www.freedesktop.org/software/systemd/man/latest/systemd-journal-gatewayd.html#Range%20header

fix: offset in log fetcher

---

rs/cli/src/commands/update_authorized_subnets.rs

If, after all the business rules are applied, no subnet changes its state from `public` to `false` or otherwise, the tool shouldn't try and submit the proposal.

feat: Skipping proposal creation if there are no subnet status changes

---

release-index.yaml

This reverts commit 9f7f0036b49151a8e46636f18ed381d33b53b931.

Revert "chore(release): remove last week's rc--2025-05-08_03-21 entry (#1559)"

---

rs/dre-canisters/node-provider-rewards/canister/api/src/endpoints.rs
rs/dre-canisters/node-provider-rewards/canister/node_provider_rewards.did
rs/dre-canisters/node-provider-rewards/canister/src/lib.rs

Changes:
- Add V1 endpoint for estimating fr daily
- Add V1 return types
- Add candid spec. for these types

chore(NRC): Add V1 endpoint and candid types

---

release-controller/forum.py

When a post is detected to differ from the expected content, log the differences before updating the post.
This is going to help us address an ongoing situation whereby a log line appears to indicate that posts are updated after a restart of the release controller, but no visible content changes appear on Discourse.
This feature will also be useful to diagnose and revert the effects of a hypothetical bad prod run whereby old posts are updated in unexpected ways.

feat(release-controller): log post differences before updating
